// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: nodes/node_service.proto

package nodes

import (
	pb "github.com/snple/beacon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLoginRequest) Reset() {
	*x = NodeLoginRequest{}
	mi := &file_nodes_node_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLoginRequest) ProtoMessage() {}

func (x *NodeLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_node_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLoginRequest.ProtoReflect.Descriptor instead.
func (*NodeLoginRequest) Descriptor() ([]byte, []int) {
	return file_nodes_node_service_proto_rawDescGZIP(), []int{0}
}

func (x *NodeLoginRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeLoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeLoginRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type NodeLoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *pb.Node               `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLoginReply) Reset() {
	*x = NodeLoginReply{}
	mi := &file_nodes_node_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLoginReply) ProtoMessage() {}

func (x *NodeLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_node_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLoginReply.ProtoReflect.Descriptor instead.
func (*NodeLoginReply) Descriptor() ([]byte, []int) {
	return file_nodes_node_service_proto_rawDescGZIP(), []int{1}
}

func (x *NodeLoginReply) GetNode() *pb.Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeLoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type NodeKeepAliveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int32                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeKeepAliveReply) Reset() {
	*x = NodeKeepAliveReply{}
	mi := &file_nodes_node_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeKeepAliveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeKeepAliveReply) ProtoMessage() {}

func (x *NodeKeepAliveReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_node_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeKeepAliveReply.ProtoReflect.Descriptor instead.
func (*NodeKeepAliveReply) Descriptor() ([]byte, []int) {
	return file_nodes_node_service_proto_rawDescGZIP(), []int{2}
}

func (x *NodeKeepAliveReply) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_nodes_node_service_proto protoreflect.FileDescriptor

const file_nodes_node_service_proto_rawDesc = "" +
	"\n" +
	"\x18nodes/node_service.proto\x12\x05nodes\x1a\x12node_message.proto\x1a\x15generic_message.proto\"N\n" +
	"\x10NodeLoginRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\"D\n" +
	"\x0eNodeLoginReply\x12\x1c\n" +
	"\x04node\x18\x01 \x01(\v2\b.pb.NodeR\x04node\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"(\n" +
	"\x12NodeKeepAliveReply\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x05R\x04time2\xc5\x01\n" +
	"\vNodeService\x129\n" +
	"\x05Login\x12\x17.nodes.NodeLoginRequest\x1a\x15.nodes.NodeLoginReply\"\x00\x12\x1f\n" +
	"\x04View\x12\v.pb.MyEmpty\x1a\b.pb.Node\"\x00\x12!\n" +
	"\x04Push\x12\v.pb.MyEmpty\x1a\n" +
	".pb.MyBool\"\x00\x127\n" +
	"\tKeepAlive\x12\v.pb.MyEmpty\x1a\x19.nodes.NodeKeepAliveReply\"\x000\x01B(Z&github.com/snple/beacon/pb/nodes;nodesb\x06proto3"

var (
	file_nodes_node_service_proto_rawDescOnce sync.Once
	file_nodes_node_service_proto_rawDescData []byte
)

func file_nodes_node_service_proto_rawDescGZIP() []byte {
	file_nodes_node_service_proto_rawDescOnce.Do(func() {
		file_nodes_node_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodes_node_service_proto_rawDesc), len(file_nodes_node_service_proto_rawDesc)))
	})
	return file_nodes_node_service_proto_rawDescData
}

var file_nodes_node_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nodes_node_service_proto_goTypes = []any{
	(*NodeLoginRequest)(nil),   // 0: nodes.NodeLoginRequest
	(*NodeLoginReply)(nil),     // 1: nodes.NodeLoginReply
	(*NodeKeepAliveReply)(nil), // 2: nodes.NodeKeepAliveReply
	(*pb.Node)(nil),            // 3: pb.Node
	(*pb.MyEmpty)(nil),         // 4: pb.MyEmpty
	(*pb.MyBool)(nil),          // 5: pb.MyBool
}
var file_nodes_node_service_proto_depIdxs = []int32{
	3, // 0: nodes.NodeLoginReply.node:type_name -> pb.Node
	0, // 1: nodes.NodeService.Login:input_type -> nodes.NodeLoginRequest
	4, // 2: nodes.NodeService.View:input_type -> pb.MyEmpty
	4, // 3: nodes.NodeService.Push:input_type -> pb.MyEmpty
	4, // 4: nodes.NodeService.KeepAlive:input_type -> pb.MyEmpty
	1, // 5: nodes.NodeService.Login:output_type -> nodes.NodeLoginReply
	3, // 6: nodes.NodeService.View:output_type -> pb.Node
	5, // 7: nodes.NodeService.Push:output_type -> pb.MyBool
	2, // 8: nodes.NodeService.KeepAlive:output_type -> nodes.NodeKeepAliveReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nodes_node_service_proto_init() }
func file_nodes_node_service_proto_init() {
	if File_nodes_node_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodes_node_service_proto_rawDesc), len(file_nodes_node_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodes_node_service_proto_goTypes,
		DependencyIndexes: file_nodes_node_service_proto_depIdxs,
		MessageInfos:      file_nodes_node_service_proto_msgTypes,
	}.Build()
	File_nodes_node_service_proto = out.File
	file_nodes_node_service_proto_goTypes = nil
	file_nodes_node_service_proto_depIdxs = nil
}
