// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: nodes/sync_service.proto

package nodes

import (
	pb "github.com/snple/beacon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Updated       int64                  `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUpdated) Reset() {
	*x = SyncUpdated{}
	mi := &file_nodes_sync_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUpdated) ProtoMessage() {}

func (x *SyncUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_sync_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUpdated.ProtoReflect.Descriptor instead.
func (*SyncUpdated) Descriptor() ([]byte, []int) {
	return file_nodes_sync_service_proto_rawDescGZIP(), []int{0}
}

func (x *SyncUpdated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncUpdated) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

var File_nodes_sync_service_proto protoreflect.FileDescriptor

const file_nodes_sync_service_proto_rawDesc = "" +
	"\n" +
	"\x18nodes/sync_service.proto\x12\x05nodes\x1a\x15generic_message.proto\"7\n" +
	"\vSyncUpdated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\x03R\aupdated2\xcc\x02\n" +
	"\vSyncService\x123\n" +
	"\x0eGetNodeUpdated\x12\v.pb.MyEmpty\x1a\x12.nodes.SyncUpdated\"\x00\x12.\n" +
	"\x0fWaitNodeUpdated\x12\v.pb.MyEmpty\x1a\n" +
	".pb.MyBool\"\x000\x01\x127\n" +
	"\x12GetPinValueUpdated\x12\v.pb.MyEmpty\x1a\x12.nodes.SyncUpdated\"\x00\x122\n" +
	"\x13WaitPinValueUpdated\x12\v.pb.MyEmpty\x1a\n" +
	".pb.MyBool\"\x000\x01\x127\n" +
	"\x12GetPinWriteUpdated\x12\v.pb.MyEmpty\x1a\x12.nodes.SyncUpdated\"\x00\x122\n" +
	"\x13WaitPinWriteUpdated\x12\v.pb.MyEmpty\x1a\n" +
	".pb.MyBool\"\x000\x01B(Z&github.com/snple/beacon/pb/nodes;nodesb\x06proto3"

var (
	file_nodes_sync_service_proto_rawDescOnce sync.Once
	file_nodes_sync_service_proto_rawDescData []byte
)

func file_nodes_sync_service_proto_rawDescGZIP() []byte {
	file_nodes_sync_service_proto_rawDescOnce.Do(func() {
		file_nodes_sync_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodes_sync_service_proto_rawDesc), len(file_nodes_sync_service_proto_rawDesc)))
	})
	return file_nodes_sync_service_proto_rawDescData
}

var file_nodes_sync_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nodes_sync_service_proto_goTypes = []any{
	(*SyncUpdated)(nil), // 0: nodes.SyncUpdated
	(*pb.MyEmpty)(nil),  // 1: pb.MyEmpty
	(*pb.MyBool)(nil),   // 2: pb.MyBool
}
var file_nodes_sync_service_proto_depIdxs = []int32{
	1, // 0: nodes.SyncService.GetNodeUpdated:input_type -> pb.MyEmpty
	1, // 1: nodes.SyncService.WaitNodeUpdated:input_type -> pb.MyEmpty
	1, // 2: nodes.SyncService.GetPinValueUpdated:input_type -> pb.MyEmpty
	1, // 3: nodes.SyncService.WaitPinValueUpdated:input_type -> pb.MyEmpty
	1, // 4: nodes.SyncService.GetPinWriteUpdated:input_type -> pb.MyEmpty
	1, // 5: nodes.SyncService.WaitPinWriteUpdated:input_type -> pb.MyEmpty
	0, // 6: nodes.SyncService.GetNodeUpdated:output_type -> nodes.SyncUpdated
	2, // 7: nodes.SyncService.WaitNodeUpdated:output_type -> pb.MyBool
	0, // 8: nodes.SyncService.GetPinValueUpdated:output_type -> nodes.SyncUpdated
	2, // 9: nodes.SyncService.WaitPinValueUpdated:output_type -> pb.MyBool
	0, // 10: nodes.SyncService.GetPinWriteUpdated:output_type -> nodes.SyncUpdated
	2, // 11: nodes.SyncService.WaitPinWriteUpdated:output_type -> pb.MyBool
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodes_sync_service_proto_init() }
func file_nodes_sync_service_proto_init() {
	if File_nodes_sync_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodes_sync_service_proto_rawDesc), len(file_nodes_sync_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodes_sync_service_proto_goTypes,
		DependencyIndexes: file_nodes_sync_service_proto_depIdxs,
		MessageInfos:      file_nodes_sync_service_proto_msgTypes,
	}.Build()
	File_nodes_sync_service_proto = out.File
	file_nodes_sync_service_proto_goTypes = nil
	file_nodes_sync_service_proto_depIdxs = nil
}
