// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: nodes/wire_service.proto

package nodes

import (
	pb "github.com/snple/beacon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// wire
type WireListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireListRequest) Reset() {
	*x = WireListRequest{}
	mi := &file_nodes_wire_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireListRequest) ProtoMessage() {}

func (x *WireListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_wire_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireListRequest.ProtoReflect.Descriptor instead.
func (*WireListRequest) Descriptor() ([]byte, []int) {
	return file_nodes_wire_service_proto_rawDescGZIP(), []int{0}
}

func (x *WireListRequest) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type WireListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Wires         []*pb.Wire             `protobuf:"bytes,3,rep,name=wires,proto3" json:"wires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireListResponse) Reset() {
	*x = WireListResponse{}
	mi := &file_nodes_wire_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireListResponse) ProtoMessage() {}

func (x *WireListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_wire_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireListResponse.ProtoReflect.Descriptor instead.
func (*WireListResponse) Descriptor() ([]byte, []int) {
	return file_nodes_wire_service_proto_rawDescGZIP(), []int{1}
}

func (x *WireListResponse) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *WireListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *WireListResponse) GetWires() []*pb.Wire {
	if x != nil {
		return x.Wires
	}
	return nil
}

// pin
type PinListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	WireId        string                 `protobuf:"bytes,3,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListRequest) Reset() {
	*x = PinListRequest{}
	mi := &file_nodes_wire_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListRequest) ProtoMessage() {}

func (x *PinListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_wire_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListRequest.ProtoReflect.Descriptor instead.
func (*PinListRequest) Descriptor() ([]byte, []int) {
	return file_nodes_wire_service_proto_rawDescGZIP(), []int{2}
}

func (x *PinListRequest) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PinListRequest) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

type PinListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Pins          []*pb.Pin              `protobuf:"bytes,3,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListResponse) Reset() {
	*x = PinListResponse{}
	mi := &file_nodes_wire_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListResponse) ProtoMessage() {}

func (x *PinListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_wire_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListResponse.ProtoReflect.Descriptor instead.
func (*PinListResponse) Descriptor() ([]byte, []int) {
	return file_nodes_wire_service_proto_rawDescGZIP(), []int{3}
}

func (x *PinListResponse) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PinListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PinListResponse) GetPins() []*pb.Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

type PinPullWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	After         int64                  `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	WireId        string                 `protobuf:"bytes,4,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinPullWriteRequest) Reset() {
	*x = PinPullWriteRequest{}
	mi := &file_nodes_wire_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinPullWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinPullWriteRequest) ProtoMessage() {}

func (x *PinPullWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodes_wire_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinPullWriteRequest.ProtoReflect.Descriptor instead.
func (*PinPullWriteRequest) Descriptor() ([]byte, []int) {
	return file_nodes_wire_service_proto_rawDescGZIP(), []int{4}
}

func (x *PinPullWriteRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *PinPullWriteRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PinPullWriteRequest) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

var File_nodes_wire_service_proto protoreflect.FileDescriptor

const file_nodes_wire_service_proto_rawDesc = "" +
	"\n" +
	"\x18nodes/wire_service.proto\x12\x05nodes\x1a\x12node_message.proto\x1a\x15generic_message.proto\"/\n" +
	"\x0fWireListRequest\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\"f\n" +
	"\x10WireListResponse\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1e\n" +
	"\x05wires\x18\x03 \x03(\v2\b.pb.WireR\x05wires\"G\n" +
	"\x0ePinListRequest\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x17\n" +
	"\awire_id\x18\x03 \x01(\tR\x06wireId\"b\n" +
	"\x0fPinListResponse\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1b\n" +
	"\x04pins\x18\x03 \x03(\v2\a.pb.PinR\x04pins\"Z\n" +
	"\x13PinPullWriteRequest\x12\x14\n" +
	"\x05after\x18\x01 \x01(\x03R\x05after\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x17\n" +
	"\awire_id\x18\x04 \x01(\tR\x06wireId2\x82\x01\n" +
	"\vWireService\x12\x1a\n" +
	"\x04View\x12\x06.pb.Id\x1a\b.pb.Wire\"\x00\x12\x1c\n" +
	"\x04Name\x12\b.pb.Name\x1a\b.pb.Wire\"\x00\x129\n" +
	"\x04List\x12\x16.nodes.WireListRequest\x1a\x17.nodes.WireListResponse\"\x002\x8a\x04\n" +
	"\n" +
	"PinService\x12\x19\n" +
	"\x04View\x12\x06.pb.Id\x1a\a.pb.Pin\"\x00\x12\x1b\n" +
	"\x04Name\x12\b.pb.Name\x1a\a.pb.Pin\"\x00\x127\n" +
	"\x04List\x12\x15.nodes.PinListRequest\x1a\x16.nodes.PinListResponse\"\x00\x12\"\n" +
	"\bGetValue\x12\x06.pb.Id\x1a\f.pb.PinValue\"\x00\x12.\n" +
	"\x0eGetValueByName\x12\b.pb.Name\x1a\x10.pb.PinNameValue\"\x00\x12)\n" +
	"\tPushValue\x12\f.pb.PinValue\x1a\n" +
	".pb.MyBool\"\x00(\x01\x12\"\n" +
	"\bGetWrite\x12\x06.pb.Id\x1a\f.pb.PinValue\"\x00\x12&\n" +
	"\bSetWrite\x12\f.pb.PinValue\x1a\n" +
	".pb.MyBool\"\x00\x12.\n" +
	"\x0eGetWriteByName\x12\b.pb.Name\x1a\x10.pb.PinNameValue\"\x00\x120\n" +
	"\x0eSetWriteByName\x12\x10.pb.PinNameValue\x1a\n" +
	".pb.MyBool\"\x00\x12#\n" +
	"\vDeleteWrite\x12\x06.pb.Id\x1a\n" +
	".pb.MyBool\"\x00\x129\n" +
	"\tPullWrite\x12\x1a.nodes.PinPullWriteRequest\x1a\f.pb.PinValue\"\x000\x01B(Z&github.com/snple/beacon/pb/nodes;nodesb\x06proto3"

var (
	file_nodes_wire_service_proto_rawDescOnce sync.Once
	file_nodes_wire_service_proto_rawDescData []byte
)

func file_nodes_wire_service_proto_rawDescGZIP() []byte {
	file_nodes_wire_service_proto_rawDescOnce.Do(func() {
		file_nodes_wire_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodes_wire_service_proto_rawDesc), len(file_nodes_wire_service_proto_rawDesc)))
	})
	return file_nodes_wire_service_proto_rawDescData
}

var file_nodes_wire_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_nodes_wire_service_proto_goTypes = []any{
	(*WireListRequest)(nil),     // 0: nodes.WireListRequest
	(*WireListResponse)(nil),    // 1: nodes.WireListResponse
	(*PinListRequest)(nil),      // 2: nodes.PinListRequest
	(*PinListResponse)(nil),     // 3: nodes.PinListResponse
	(*PinPullWriteRequest)(nil), // 4: nodes.PinPullWriteRequest
	(*pb.Page)(nil),             // 5: pb.Page
	(*pb.Wire)(nil),             // 6: pb.Wire
	(*pb.Pin)(nil),              // 7: pb.Pin
	(*pb.Id)(nil),               // 8: pb.Id
	(*pb.Name)(nil),             // 9: pb.Name
	(*pb.PinValue)(nil),         // 10: pb.PinValue
	(*pb.PinNameValue)(nil),     // 11: pb.PinNameValue
	(*pb.MyBool)(nil),           // 12: pb.MyBool
}
var file_nodes_wire_service_proto_depIdxs = []int32{
	5,  // 0: nodes.WireListRequest.page:type_name -> pb.Page
	5,  // 1: nodes.WireListResponse.page:type_name -> pb.Page
	6,  // 2: nodes.WireListResponse.wires:type_name -> pb.Wire
	5,  // 3: nodes.PinListRequest.page:type_name -> pb.Page
	5,  // 4: nodes.PinListResponse.page:type_name -> pb.Page
	7,  // 5: nodes.PinListResponse.pins:type_name -> pb.Pin
	8,  // 6: nodes.WireService.View:input_type -> pb.Id
	9,  // 7: nodes.WireService.Name:input_type -> pb.Name
	0,  // 8: nodes.WireService.List:input_type -> nodes.WireListRequest
	8,  // 9: nodes.PinService.View:input_type -> pb.Id
	9,  // 10: nodes.PinService.Name:input_type -> pb.Name
	2,  // 11: nodes.PinService.List:input_type -> nodes.PinListRequest
	8,  // 12: nodes.PinService.GetValue:input_type -> pb.Id
	9,  // 13: nodes.PinService.GetValueByName:input_type -> pb.Name
	10, // 14: nodes.PinService.PushValue:input_type -> pb.PinValue
	8,  // 15: nodes.PinService.GetWrite:input_type -> pb.Id
	10, // 16: nodes.PinService.SetWrite:input_type -> pb.PinValue
	9,  // 17: nodes.PinService.GetWriteByName:input_type -> pb.Name
	11, // 18: nodes.PinService.SetWriteByName:input_type -> pb.PinNameValue
	8,  // 19: nodes.PinService.DeleteWrite:input_type -> pb.Id
	4,  // 20: nodes.PinService.PullWrite:input_type -> nodes.PinPullWriteRequest
	6,  // 21: nodes.WireService.View:output_type -> pb.Wire
	6,  // 22: nodes.WireService.Name:output_type -> pb.Wire
	1,  // 23: nodes.WireService.List:output_type -> nodes.WireListResponse
	7,  // 24: nodes.PinService.View:output_type -> pb.Pin
	7,  // 25: nodes.PinService.Name:output_type -> pb.Pin
	3,  // 26: nodes.PinService.List:output_type -> nodes.PinListResponse
	10, // 27: nodes.PinService.GetValue:output_type -> pb.PinValue
	11, // 28: nodes.PinService.GetValueByName:output_type -> pb.PinNameValue
	12, // 29: nodes.PinService.PushValue:output_type -> pb.MyBool
	10, // 30: nodes.PinService.GetWrite:output_type -> pb.PinValue
	12, // 31: nodes.PinService.SetWrite:output_type -> pb.MyBool
	11, // 32: nodes.PinService.GetWriteByName:output_type -> pb.PinNameValue
	12, // 33: nodes.PinService.SetWriteByName:output_type -> pb.MyBool
	12, // 34: nodes.PinService.DeleteWrite:output_type -> pb.MyBool
	10, // 35: nodes.PinService.PullWrite:output_type -> pb.PinValue
	21, // [21:36] is the sub-list for method output_type
	6,  // [6:21] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_nodes_wire_service_proto_init() }
func file_nodes_wire_service_proto_init() {
	if File_nodes_wire_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodes_wire_service_proto_rawDesc), len(file_nodes_wire_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_nodes_wire_service_proto_goTypes,
		DependencyIndexes: file_nodes_wire_service_proto_depIdxs,
		MessageInfos:      file_nodes_wire_service_proto_msgTypes,
	}.Build()
	File_nodes_wire_service_proto = out.File
	file_nodes_wire_service_proto_goTypes = nil
	file_nodes_wire_service_proto_depIdxs = nil
}
