// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: nodes/wire_service.proto

package nodes

import (
	context "context"
	pb "github.com/snple/beacon/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WireService_View_FullMethodName = "/nodes.WireService/View"
	WireService_Name_FullMethodName = "/nodes.WireService/Name"
	WireService_List_FullMethodName = "/nodes.WireService/List"
)

// WireServiceClient is the client API for WireService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WireServiceClient interface {
	View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Wire, error)
	Name(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Wire, error)
	List(ctx context.Context, in *WireListRequest, opts ...grpc.CallOption) (*WireListResponse, error)
}

type wireServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWireServiceClient(cc grpc.ClientConnInterface) WireServiceClient {
	return &wireServiceClient{cc}
}

func (c *wireServiceClient) View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Wire, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Wire)
	err := c.cc.Invoke(ctx, WireService_View_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) Name(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Wire, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Wire)
	err := c.cc.Invoke(ctx, WireService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) List(ctx context.Context, in *WireListRequest, opts ...grpc.CallOption) (*WireListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireListResponse)
	err := c.cc.Invoke(ctx, WireService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireServiceServer is the server API for WireService service.
// All implementations must embed UnimplementedWireServiceServer
// for forward compatibility.
type WireServiceServer interface {
	View(context.Context, *pb.Id) (*pb.Wire, error)
	Name(context.Context, *pb.Name) (*pb.Wire, error)
	List(context.Context, *WireListRequest) (*WireListResponse, error)
	mustEmbedUnimplementedWireServiceServer()
}

// UnimplementedWireServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWireServiceServer struct{}

func (UnimplementedWireServiceServer) View(context.Context, *pb.Id) (*pb.Wire, error) {
	return nil, status.Error(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedWireServiceServer) Name(context.Context, *pb.Name) (*pb.Wire, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedWireServiceServer) List(context.Context, *WireListRequest) (*WireListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedWireServiceServer) mustEmbedUnimplementedWireServiceServer() {}
func (UnimplementedWireServiceServer) testEmbeddedByValue()                     {}

// UnsafeWireServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WireServiceServer will
// result in compilation errors.
type UnsafeWireServiceServer interface {
	mustEmbedUnimplementedWireServiceServer()
}

func RegisterWireServiceServer(s grpc.ServiceRegistrar, srv WireServiceServer) {
	// If the following call panics, it indicates UnimplementedWireServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WireService_ServiceDesc, srv)
}

func _WireService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).View(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).Name(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).List(ctx, req.(*WireListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WireService_ServiceDesc is the grpc.ServiceDesc for WireService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WireService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodes.WireService",
	HandlerType: (*WireServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "View",
			Handler:    _WireService_View_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _WireService_Name_Handler,
		},
		{
			MethodName: "List",
			Handler:    _WireService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodes/wire_service.proto",
}

const (
	PinService_View_FullMethodName           = "/nodes.PinService/View"
	PinService_Name_FullMethodName           = "/nodes.PinService/Name"
	PinService_List_FullMethodName           = "/nodes.PinService/List"
	PinService_GetValue_FullMethodName       = "/nodes.PinService/GetValue"
	PinService_GetValueByName_FullMethodName = "/nodes.PinService/GetValueByName"
	PinService_PushValue_FullMethodName      = "/nodes.PinService/PushValue"
	PinService_GetWrite_FullMethodName       = "/nodes.PinService/GetWrite"
	PinService_SetWrite_FullMethodName       = "/nodes.PinService/SetWrite"
	PinService_GetWriteByName_FullMethodName = "/nodes.PinService/GetWriteByName"
	PinService_SetWriteByName_FullMethodName = "/nodes.PinService/SetWriteByName"
	PinService_DeleteWrite_FullMethodName    = "/nodes.PinService/DeleteWrite"
	PinService_PullWrite_FullMethodName      = "/nodes.PinService/PullWrite"
)

// PinServiceClient is the client API for PinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PinServiceClient interface {
	View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Pin, error)
	Name(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Pin, error)
	List(ctx context.Context, in *PinListRequest, opts ...grpc.CallOption) (*PinListResponse, error)
	GetValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValue, error)
	GetValueByName(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.PinNameValue, error)
	PushValue(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.PinValue, pb.MyBool], error)
	GetWrite(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValue, error)
	SetWrite(ctx context.Context, in *pb.PinValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	GetWriteByName(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.PinNameValue, error)
	SetWriteByName(ctx context.Context, in *pb.PinNameValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	DeleteWrite(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error)
	PullWrite(ctx context.Context, in *PinPullWriteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.PinValue], error)
}

type pinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPinServiceClient(cc grpc.ClientConnInterface) PinServiceClient {
	return &pinServiceClient{cc}
}

func (c *pinServiceClient) View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Pin, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Pin)
	err := c.cc.Invoke(ctx, PinService_View_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) Name(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Pin, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Pin)
	err := c.cc.Invoke(ctx, PinService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) List(ctx context.Context, in *PinListRequest, opts ...grpc.CallOption) (*PinListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PinListResponse)
	err := c.cc.Invoke(ctx, PinService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) GetValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.PinValue)
	err := c.cc.Invoke(ctx, PinService_GetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) GetValueByName(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.PinNameValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.PinNameValue)
	err := c.cc.Invoke(ctx, PinService_GetValueByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) PushValue(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.PinValue, pb.MyBool], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PinService_ServiceDesc.Streams[0], PinService_PushValue_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.PinValue, pb.MyBool]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PinService_PushValueClient = grpc.ClientStreamingClient[pb.PinValue, pb.MyBool]

func (c *pinServiceClient) GetWrite(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.PinValue)
	err := c.cc.Invoke(ctx, PinService_GetWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) SetWrite(ctx context.Context, in *pb.PinValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, PinService_SetWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) GetWriteByName(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.PinNameValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.PinNameValue)
	err := c.cc.Invoke(ctx, PinService_GetWriteByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) SetWriteByName(ctx context.Context, in *pb.PinNameValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, PinService_SetWriteByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) DeleteWrite(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, PinService_DeleteWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) PullWrite(ctx context.Context, in *PinPullWriteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.PinValue], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PinService_ServiceDesc.Streams[1], PinService_PullWrite_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PinPullWriteRequest, pb.PinValue]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PinService_PullWriteClient = grpc.ServerStreamingClient[pb.PinValue]

// PinServiceServer is the server API for PinService service.
// All implementations must embed UnimplementedPinServiceServer
// for forward compatibility.
type PinServiceServer interface {
	View(context.Context, *pb.Id) (*pb.Pin, error)
	Name(context.Context, *pb.Name) (*pb.Pin, error)
	List(context.Context, *PinListRequest) (*PinListResponse, error)
	GetValue(context.Context, *pb.Id) (*pb.PinValue, error)
	GetValueByName(context.Context, *pb.Name) (*pb.PinNameValue, error)
	PushValue(grpc.ClientStreamingServer[pb.PinValue, pb.MyBool]) error
	GetWrite(context.Context, *pb.Id) (*pb.PinValue, error)
	SetWrite(context.Context, *pb.PinValue) (*pb.MyBool, error)
	GetWriteByName(context.Context, *pb.Name) (*pb.PinNameValue, error)
	SetWriteByName(context.Context, *pb.PinNameValue) (*pb.MyBool, error)
	DeleteWrite(context.Context, *pb.Id) (*pb.MyBool, error)
	PullWrite(*PinPullWriteRequest, grpc.ServerStreamingServer[pb.PinValue]) error
	mustEmbedUnimplementedPinServiceServer()
}

// UnimplementedPinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPinServiceServer struct{}

func (UnimplementedPinServiceServer) View(context.Context, *pb.Id) (*pb.Pin, error) {
	return nil, status.Error(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedPinServiceServer) Name(context.Context, *pb.Name) (*pb.Pin, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedPinServiceServer) List(context.Context, *PinListRequest) (*PinListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPinServiceServer) GetValue(context.Context, *pb.Id) (*pb.PinValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedPinServiceServer) GetValueByName(context.Context, *pb.Name) (*pb.PinNameValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValueByName not implemented")
}
func (UnimplementedPinServiceServer) PushValue(grpc.ClientStreamingServer[pb.PinValue, pb.MyBool]) error {
	return status.Error(codes.Unimplemented, "method PushValue not implemented")
}
func (UnimplementedPinServiceServer) GetWrite(context.Context, *pb.Id) (*pb.PinValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWrite not implemented")
}
func (UnimplementedPinServiceServer) SetWrite(context.Context, *pb.PinValue) (*pb.MyBool, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWrite not implemented")
}
func (UnimplementedPinServiceServer) GetWriteByName(context.Context, *pb.Name) (*pb.PinNameValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWriteByName not implemented")
}
func (UnimplementedPinServiceServer) SetWriteByName(context.Context, *pb.PinNameValue) (*pb.MyBool, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWriteByName not implemented")
}
func (UnimplementedPinServiceServer) DeleteWrite(context.Context, *pb.Id) (*pb.MyBool, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWrite not implemented")
}
func (UnimplementedPinServiceServer) PullWrite(*PinPullWriteRequest, grpc.ServerStreamingServer[pb.PinValue]) error {
	return status.Error(codes.Unimplemented, "method PullWrite not implemented")
}
func (UnimplementedPinServiceServer) mustEmbedUnimplementedPinServiceServer() {}
func (UnimplementedPinServiceServer) testEmbeddedByValue()                    {}

// UnsafePinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PinServiceServer will
// result in compilation errors.
type UnsafePinServiceServer interface {
	mustEmbedUnimplementedPinServiceServer()
}

func RegisterPinServiceServer(s grpc.ServiceRegistrar, srv PinServiceServer) {
	// If the following call panics, it indicates UnimplementedPinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PinService_ServiceDesc, srv)
}

func _PinService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).View(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).Name(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).List(ctx, req.(*PinListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).GetValue(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_GetValueByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).GetValueByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_GetValueByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).GetValueByName(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_PushValue_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PinServiceServer).PushValue(&grpc.GenericServerStream[pb.PinValue, pb.MyBool]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PinService_PushValueServer = grpc.ClientStreamingServer[pb.PinValue, pb.MyBool]

func _PinService_GetWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).GetWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_GetWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).GetWrite(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_SetWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.PinValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).SetWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_SetWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).SetWrite(ctx, req.(*pb.PinValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_GetWriteByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).GetWriteByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_GetWriteByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).GetWriteByName(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_SetWriteByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.PinNameValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).SetWriteByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_SetWriteByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).SetWriteByName(ctx, req.(*pb.PinNameValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_DeleteWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).DeleteWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_DeleteWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).DeleteWrite(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_PullWrite_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PinPullWriteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PinServiceServer).PullWrite(m, &grpc.GenericServerStream[PinPullWriteRequest, pb.PinValue]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PinService_PullWriteServer = grpc.ServerStreamingServer[pb.PinValue]

// PinService_ServiceDesc is the grpc.ServiceDesc for PinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodes.PinService",
	HandlerType: (*PinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "View",
			Handler:    _PinService_View_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _PinService_Name_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PinService_List_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _PinService_GetValue_Handler,
		},
		{
			MethodName: "GetValueByName",
			Handler:    _PinService_GetValueByName_Handler,
		},
		{
			MethodName: "GetWrite",
			Handler:    _PinService_GetWrite_Handler,
		},
		{
			MethodName: "SetWrite",
			Handler:    _PinService_SetWrite_Handler,
		},
		{
			MethodName: "GetWriteByName",
			Handler:    _PinService_GetWriteByName_Handler,
		},
		{
			MethodName: "SetWriteByName",
			Handler:    _PinService_SetWriteByName_Handler,
		},
		{
			MethodName: "DeleteWrite",
			Handler:    _PinService_DeleteWrite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushValue",
			Handler:       _PinService_PushValue_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PullWrite",
			Handler:       _PinService_PullWrite_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nodes/wire_service.proto",
}
