// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: edges/node_service.proto

package edges

import (
	pb "github.com/snple/beacon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_edges_node_service_proto protoreflect.FileDescriptor

const file_edges_node_service_proto_rawDesc = "" +
	"\n" +
	"\x18edges/node_service.proto\x12\x05edges\x1a\x12node_message.proto\x1a\x15generic_message.proto2.\n" +
	"\vNodeService\x12\x1f\n" +
	"\x04View\x12\v.pb.MyEmpty\x1a\b.pb.Node\"\x00B(Z&github.com/snple/beacon/pb/edges;edgesb\x06proto3"

var file_edges_node_service_proto_goTypes = []any{
	(*pb.MyEmpty)(nil), // 0: pb.MyEmpty
	(*pb.Node)(nil),    // 1: pb.Node
}
var file_edges_node_service_proto_depIdxs = []int32{
	0, // 0: edges.NodeService.View:input_type -> pb.MyEmpty
	1, // 1: edges.NodeService.View:output_type -> pb.Node
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_edges_node_service_proto_init() }
func file_edges_node_service_proto_init() {
	if File_edges_node_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edges_node_service_proto_rawDesc), len(file_edges_node_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edges_node_service_proto_goTypes,
		DependencyIndexes: file_edges_node_service_proto_depIdxs,
	}.Build()
	File_edges_node_service_proto = out.File
	file_edges_node_service_proto_goTypes = nil
	file_edges_node_service_proto_depIdxs = nil
}
