// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: edges/wire_service.proto

package edges

import (
	pb "github.com/snple/beacon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// wire
type WireListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Page  *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	// string node_id = 2;
	Tags          string `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	Source        string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireListRequest) Reset() {
	*x = WireListRequest{}
	mi := &file_edges_wire_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireListRequest) ProtoMessage() {}

func (x *WireListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edges_wire_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireListRequest.ProtoReflect.Descriptor instead.
func (*WireListRequest) Descriptor() ([]byte, []int) {
	return file_edges_wire_service_proto_rawDescGZIP(), []int{0}
}

func (x *WireListRequest) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *WireListRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *WireListRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type WireListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Wires         []*pb.Wire             `protobuf:"bytes,3,rep,name=wires,proto3" json:"wires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireListResponse) Reset() {
	*x = WireListResponse{}
	mi := &file_edges_wire_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireListResponse) ProtoMessage() {}

func (x *WireListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edges_wire_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireListResponse.ProtoReflect.Descriptor instead.
func (*WireListResponse) Descriptor() ([]byte, []int) {
	return file_edges_wire_service_proto_rawDescGZIP(), []int{1}
}

func (x *WireListResponse) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *WireListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *WireListResponse) GetWires() []*pb.Wire {
	if x != nil {
		return x.Wires
	}
	return nil
}

// pin
type PinListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Page  *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	// string node_id = 2;
	WireId        string `protobuf:"bytes,3,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	Tags          string `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListRequest) Reset() {
	*x = PinListRequest{}
	mi := &file_edges_wire_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListRequest) ProtoMessage() {}

func (x *PinListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edges_wire_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListRequest.ProtoReflect.Descriptor instead.
func (*PinListRequest) Descriptor() ([]byte, []int) {
	return file_edges_wire_service_proto_rawDescGZIP(), []int{2}
}

func (x *PinListRequest) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PinListRequest) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

func (x *PinListRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type PinListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Pins          []*pb.Pin              `protobuf:"bytes,3,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListResponse) Reset() {
	*x = PinListResponse{}
	mi := &file_edges_wire_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListResponse) ProtoMessage() {}

func (x *PinListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edges_wire_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListResponse.ProtoReflect.Descriptor instead.
func (*PinListResponse) Descriptor() ([]byte, []int) {
	return file_edges_wire_service_proto_rawDescGZIP(), []int{3}
}

func (x *PinListResponse) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PinListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PinListResponse) GetPins() []*pb.Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

type PinPullValueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	After int64                  `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
	Limit uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// string node_id = 3;
	WireId        string `protobuf:"bytes,4,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinPullValueRequest) Reset() {
	*x = PinPullValueRequest{}
	mi := &file_edges_wire_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinPullValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinPullValueRequest) ProtoMessage() {}

func (x *PinPullValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edges_wire_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinPullValueRequest.ProtoReflect.Descriptor instead.
func (*PinPullValueRequest) Descriptor() ([]byte, []int) {
	return file_edges_wire_service_proto_rawDescGZIP(), []int{4}
}

func (x *PinPullValueRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *PinPullValueRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PinPullValueRequest) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

var File_edges_wire_service_proto protoreflect.FileDescriptor

const file_edges_wire_service_proto_rawDesc = "" +
	"\n" +
	"\x18edges/wire_service.proto\x12\x05edges\x1a\x12wire_message.proto\x1a\x15generic_message.proto\"[\n" +
	"\x0fWireListRequest\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x12\n" +
	"\x04tags\x18\x03 \x01(\tR\x04tags\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"f\n" +
	"\x10WireListResponse\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1e\n" +
	"\x05wires\x18\x03 \x03(\v2\b.pb.WireR\x05wires\"[\n" +
	"\x0ePinListRequest\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x17\n" +
	"\awire_id\x18\x03 \x01(\tR\x06wireId\x12\x12\n" +
	"\x04tags\x18\x04 \x01(\tR\x04tags\"b\n" +
	"\x0fPinListResponse\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1b\n" +
	"\x04pins\x18\x03 \x03(\v2\a.pb.PinR\x04pins\"Z\n" +
	"\x13PinPullValueRequest\x12\x14\n" +
	"\x05after\x18\x01 \x01(\x03R\x05after\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x17\n" +
	"\awire_id\x18\x04 \x01(\tR\x06wireId2\x82\x01\n" +
	"\vWireService\x12\x1a\n" +
	"\x04View\x12\x06.pb.Id\x1a\b.pb.Wire\"\x00\x12\x1c\n" +
	"\x04Name\x12\b.pb.Name\x1a\b.pb.Wire\"\x00\x129\n" +
	"\x04List\x12\x16.edges.WireListRequest\x1a\x17.edges.WireListResponse\"\x002\xf0\x04\n" +
	"\n" +
	"PinService\x12\x19\n" +
	"\x04View\x12\x06.pb.Id\x1a\a.pb.Pin\"\x00\x12\x1b\n" +
	"\x04Name\x12\b.pb.Name\x1a\a.pb.Pin\"\x00\x127\n" +
	"\x04List\x12\x15.edges.PinListRequest\x1a\x16.edges.PinListResponse\"\x00\x12\"\n" +
	"\bGetValue\x12\x06.pb.Id\x1a\f.pb.PinValue\"\x00\x12&\n" +
	"\bSetValue\x12\f.pb.PinValue\x1a\n" +
	".pb.MyBool\"\x00\x12.\n" +
	"\x0eGetValueByName\x12\b.pb.Name\x1a\x10.pb.PinNameValue\"\x00\x120\n" +
	"\x0eSetValueByName\x12\x10.pb.PinNameValue\x1a\n" +
	".pb.MyBool\"\x00\x12*\n" +
	"\tViewValue\x12\x06.pb.Id\x1a\x13.pb.PinValueUpdated\"\x00\x12#\n" +
	"\vDeleteValue\x12\x06.pb.Id\x1a\n" +
	".pb.MyBool\"\x00\x12@\n" +
	"\tPullValue\x12\x1a.edges.PinPullValueRequest\x1a\x13.pb.PinValueUpdated\"\x000\x01\x12\"\n" +
	"\bGetWrite\x12\x06.pb.Id\x1a\f.pb.PinValue\"\x00\x12.\n" +
	"\x0eGetWriteByName\x12\b.pb.Name\x1a\x10.pb.PinNameValue\"\x00\x12*\n" +
	"\tViewWrite\x12\x06.pb.Id\x1a\x13.pb.PinValueUpdated\"\x00\x120\n" +
	"\tPushWrite\x12\x13.pb.PinValueUpdated\x1a\n" +
	".pb.MyBool\"\x00(\x01B(Z&github.com/snple/beacon/pb/edges;edgesb\x06proto3"

var (
	file_edges_wire_service_proto_rawDescOnce sync.Once
	file_edges_wire_service_proto_rawDescData []byte
)

func file_edges_wire_service_proto_rawDescGZIP() []byte {
	file_edges_wire_service_proto_rawDescOnce.Do(func() {
		file_edges_wire_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edges_wire_service_proto_rawDesc), len(file_edges_wire_service_proto_rawDesc)))
	})
	return file_edges_wire_service_proto_rawDescData
}

var file_edges_wire_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_edges_wire_service_proto_goTypes = []any{
	(*WireListRequest)(nil),     // 0: edges.WireListRequest
	(*WireListResponse)(nil),    // 1: edges.WireListResponse
	(*PinListRequest)(nil),      // 2: edges.PinListRequest
	(*PinListResponse)(nil),     // 3: edges.PinListResponse
	(*PinPullValueRequest)(nil), // 4: edges.PinPullValueRequest
	(*pb.Page)(nil),             // 5: pb.Page
	(*pb.Wire)(nil),             // 6: pb.Wire
	(*pb.Pin)(nil),              // 7: pb.Pin
	(*pb.Id)(nil),               // 8: pb.Id
	(*pb.Name)(nil),             // 9: pb.Name
	(*pb.PinValue)(nil),         // 10: pb.PinValue
	(*pb.PinNameValue)(nil),     // 11: pb.PinNameValue
	(*pb.PinValueUpdated)(nil),  // 12: pb.PinValueUpdated
	(*pb.MyBool)(nil),           // 13: pb.MyBool
}
var file_edges_wire_service_proto_depIdxs = []int32{
	5,  // 0: edges.WireListRequest.page:type_name -> pb.Page
	5,  // 1: edges.WireListResponse.page:type_name -> pb.Page
	6,  // 2: edges.WireListResponse.wires:type_name -> pb.Wire
	5,  // 3: edges.PinListRequest.page:type_name -> pb.Page
	5,  // 4: edges.PinListResponse.page:type_name -> pb.Page
	7,  // 5: edges.PinListResponse.pins:type_name -> pb.Pin
	8,  // 6: edges.WireService.View:input_type -> pb.Id
	9,  // 7: edges.WireService.Name:input_type -> pb.Name
	0,  // 8: edges.WireService.List:input_type -> edges.WireListRequest
	8,  // 9: edges.PinService.View:input_type -> pb.Id
	9,  // 10: edges.PinService.Name:input_type -> pb.Name
	2,  // 11: edges.PinService.List:input_type -> edges.PinListRequest
	8,  // 12: edges.PinService.GetValue:input_type -> pb.Id
	10, // 13: edges.PinService.SetValue:input_type -> pb.PinValue
	9,  // 14: edges.PinService.GetValueByName:input_type -> pb.Name
	11, // 15: edges.PinService.SetValueByName:input_type -> pb.PinNameValue
	8,  // 16: edges.PinService.ViewValue:input_type -> pb.Id
	8,  // 17: edges.PinService.DeleteValue:input_type -> pb.Id
	4,  // 18: edges.PinService.PullValue:input_type -> edges.PinPullValueRequest
	8,  // 19: edges.PinService.GetWrite:input_type -> pb.Id
	9,  // 20: edges.PinService.GetWriteByName:input_type -> pb.Name
	8,  // 21: edges.PinService.ViewWrite:input_type -> pb.Id
	12, // 22: edges.PinService.PushWrite:input_type -> pb.PinValueUpdated
	6,  // 23: edges.WireService.View:output_type -> pb.Wire
	6,  // 24: edges.WireService.Name:output_type -> pb.Wire
	1,  // 25: edges.WireService.List:output_type -> edges.WireListResponse
	7,  // 26: edges.PinService.View:output_type -> pb.Pin
	7,  // 27: edges.PinService.Name:output_type -> pb.Pin
	3,  // 28: edges.PinService.List:output_type -> edges.PinListResponse
	10, // 29: edges.PinService.GetValue:output_type -> pb.PinValue
	13, // 30: edges.PinService.SetValue:output_type -> pb.MyBool
	11, // 31: edges.PinService.GetValueByName:output_type -> pb.PinNameValue
	13, // 32: edges.PinService.SetValueByName:output_type -> pb.MyBool
	12, // 33: edges.PinService.ViewValue:output_type -> pb.PinValueUpdated
	13, // 34: edges.PinService.DeleteValue:output_type -> pb.MyBool
	12, // 35: edges.PinService.PullValue:output_type -> pb.PinValueUpdated
	10, // 36: edges.PinService.GetWrite:output_type -> pb.PinValue
	11, // 37: edges.PinService.GetWriteByName:output_type -> pb.PinNameValue
	12, // 38: edges.PinService.ViewWrite:output_type -> pb.PinValueUpdated
	13, // 39: edges.PinService.PushWrite:output_type -> pb.MyBool
	23, // [23:40] is the sub-list for method output_type
	6,  // [6:23] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_edges_wire_service_proto_init() }
func file_edges_wire_service_proto_init() {
	if File_edges_wire_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edges_wire_service_proto_rawDesc), len(file_edges_wire_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_edges_wire_service_proto_goTypes,
		DependencyIndexes: file_edges_wire_service_proto_depIdxs,
		MessageInfos:      file_edges_wire_service_proto_msgTypes,
	}.Build()
	File_edges_wire_service_proto = out.File
	file_edges_wire_service_proto_goTypes = nil
	file_edges_wire_service_proto_depIdxs = nil
}
