// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: edges/wire_service.proto

package edges

import (
	context "context"
	pb "github.com/snple/beacon/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WireService_View_FullMethodName = "/edges.WireService/View"
	WireService_Name_FullMethodName = "/edges.WireService/Name"
	WireService_List_FullMethodName = "/edges.WireService/List"
)

// WireServiceClient is the client API for WireService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WireServiceClient interface {
	View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Wire, error)
	Name(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Wire, error)
	List(ctx context.Context, in *WireListRequest, opts ...grpc.CallOption) (*WireListResponse, error)
}

type wireServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWireServiceClient(cc grpc.ClientConnInterface) WireServiceClient {
	return &wireServiceClient{cc}
}

func (c *wireServiceClient) View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Wire, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Wire)
	err := c.cc.Invoke(ctx, WireService_View_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) Name(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Wire, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Wire)
	err := c.cc.Invoke(ctx, WireService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) List(ctx context.Context, in *WireListRequest, opts ...grpc.CallOption) (*WireListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireListResponse)
	err := c.cc.Invoke(ctx, WireService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireServiceServer is the server API for WireService service.
// All implementations must embed UnimplementedWireServiceServer
// for forward compatibility.
type WireServiceServer interface {
	View(context.Context, *pb.Id) (*pb.Wire, error)
	Name(context.Context, *pb.Name) (*pb.Wire, error)
	List(context.Context, *WireListRequest) (*WireListResponse, error)
	mustEmbedUnimplementedWireServiceServer()
}

// UnimplementedWireServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWireServiceServer struct{}

func (UnimplementedWireServiceServer) View(context.Context, *pb.Id) (*pb.Wire, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedWireServiceServer) Name(context.Context, *pb.Name) (*pb.Wire, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedWireServiceServer) List(context.Context, *WireListRequest) (*WireListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedWireServiceServer) mustEmbedUnimplementedWireServiceServer() {}
func (UnimplementedWireServiceServer) testEmbeddedByValue()                     {}

// UnsafeWireServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WireServiceServer will
// result in compilation errors.
type UnsafeWireServiceServer interface {
	mustEmbedUnimplementedWireServiceServer()
}

func RegisterWireServiceServer(s grpc.ServiceRegistrar, srv WireServiceServer) {
	// If the following call pancis, it indicates UnimplementedWireServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WireService_ServiceDesc, srv)
}

func _WireService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).View(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).Name(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).List(ctx, req.(*WireListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WireService_ServiceDesc is the grpc.ServiceDesc for WireService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WireService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edges.WireService",
	HandlerType: (*WireServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "View",
			Handler:    _WireService_View_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _WireService_Name_Handler,
		},
		{
			MethodName: "List",
			Handler:    _WireService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edges/wire_service.proto",
}

const (
	PinService_View_FullMethodName           = "/edges.PinService/View"
	PinService_Name_FullMethodName           = "/edges.PinService/Name"
	PinService_List_FullMethodName           = "/edges.PinService/List"
	PinService_GetValue_FullMethodName       = "/edges.PinService/GetValue"
	PinService_SetValue_FullMethodName       = "/edges.PinService/SetValue"
	PinService_GetValueByName_FullMethodName = "/edges.PinService/GetValueByName"
	PinService_SetValueByName_FullMethodName = "/edges.PinService/SetValueByName"
	PinService_ViewValue_FullMethodName      = "/edges.PinService/ViewValue"
	PinService_DeleteValue_FullMethodName    = "/edges.PinService/DeleteValue"
	PinService_PullValue_FullMethodName      = "/edges.PinService/PullValue"
	PinService_GetWrite_FullMethodName       = "/edges.PinService/GetWrite"
	PinService_GetWriteByName_FullMethodName = "/edges.PinService/GetWriteByName"
	PinService_ViewWrite_FullMethodName      = "/edges.PinService/ViewWrite"
	PinService_PushWrite_FullMethodName      = "/edges.PinService/PushWrite"
)

// PinServiceClient is the client API for PinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PinServiceClient interface {
	View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Pin, error)
	Name(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Pin, error)
	List(ctx context.Context, in *PinListRequest, opts ...grpc.CallOption) (*PinListResponse, error)
	GetValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValue, error)
	SetValue(ctx context.Context, in *pb.PinValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	GetValueByName(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.PinNameValue, error)
	SetValueByName(ctx context.Context, in *pb.PinNameValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	ViewValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValueUpdated, error)
	DeleteValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error)
	PullValue(ctx context.Context, in *PinPullValueRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.PinValueUpdated], error)
	GetWrite(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValue, error)
	GetWriteByName(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.PinNameValue, error)
	ViewWrite(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValueUpdated, error)
	PushWrite(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.PinValueUpdated, pb.MyBool], error)
}

type pinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPinServiceClient(cc grpc.ClientConnInterface) PinServiceClient {
	return &pinServiceClient{cc}
}

func (c *pinServiceClient) View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Pin, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Pin)
	err := c.cc.Invoke(ctx, PinService_View_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) Name(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Pin, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Pin)
	err := c.cc.Invoke(ctx, PinService_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) List(ctx context.Context, in *PinListRequest, opts ...grpc.CallOption) (*PinListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PinListResponse)
	err := c.cc.Invoke(ctx, PinService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) GetValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.PinValue)
	err := c.cc.Invoke(ctx, PinService_GetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) SetValue(ctx context.Context, in *pb.PinValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, PinService_SetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) GetValueByName(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.PinNameValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.PinNameValue)
	err := c.cc.Invoke(ctx, PinService_GetValueByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) SetValueByName(ctx context.Context, in *pb.PinNameValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, PinService_SetValueByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) ViewValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValueUpdated, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.PinValueUpdated)
	err := c.cc.Invoke(ctx, PinService_ViewValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) DeleteValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, PinService_DeleteValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) PullValue(ctx context.Context, in *PinPullValueRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.PinValueUpdated], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PinService_ServiceDesc.Streams[0], PinService_PullValue_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PinPullValueRequest, pb.PinValueUpdated]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PinService_PullValueClient = grpc.ServerStreamingClient[pb.PinValueUpdated]

func (c *pinServiceClient) GetWrite(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.PinValue)
	err := c.cc.Invoke(ctx, PinService_GetWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) GetWriteByName(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.PinNameValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.PinNameValue)
	err := c.cc.Invoke(ctx, PinService_GetWriteByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) ViewWrite(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.PinValueUpdated, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.PinValueUpdated)
	err := c.cc.Invoke(ctx, PinService_ViewWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pinServiceClient) PushWrite(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.PinValueUpdated, pb.MyBool], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PinService_ServiceDesc.Streams[1], PinService_PushWrite_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.PinValueUpdated, pb.MyBool]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PinService_PushWriteClient = grpc.ClientStreamingClient[pb.PinValueUpdated, pb.MyBool]

// PinServiceServer is the server API for PinService service.
// All implementations must embed UnimplementedPinServiceServer
// for forward compatibility.
type PinServiceServer interface {
	View(context.Context, *pb.Id) (*pb.Pin, error)
	Name(context.Context, *pb.Name) (*pb.Pin, error)
	List(context.Context, *PinListRequest) (*PinListResponse, error)
	GetValue(context.Context, *pb.Id) (*pb.PinValue, error)
	SetValue(context.Context, *pb.PinValue) (*pb.MyBool, error)
	GetValueByName(context.Context, *pb.Name) (*pb.PinNameValue, error)
	SetValueByName(context.Context, *pb.PinNameValue) (*pb.MyBool, error)
	ViewValue(context.Context, *pb.Id) (*pb.PinValueUpdated, error)
	DeleteValue(context.Context, *pb.Id) (*pb.MyBool, error)
	PullValue(*PinPullValueRequest, grpc.ServerStreamingServer[pb.PinValueUpdated]) error
	GetWrite(context.Context, *pb.Id) (*pb.PinValue, error)
	GetWriteByName(context.Context, *pb.Name) (*pb.PinNameValue, error)
	ViewWrite(context.Context, *pb.Id) (*pb.PinValueUpdated, error)
	PushWrite(grpc.ClientStreamingServer[pb.PinValueUpdated, pb.MyBool]) error
	mustEmbedUnimplementedPinServiceServer()
}

// UnimplementedPinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPinServiceServer struct{}

func (UnimplementedPinServiceServer) View(context.Context, *pb.Id) (*pb.Pin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedPinServiceServer) Name(context.Context, *pb.Name) (*pb.Pin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedPinServiceServer) List(context.Context, *PinListRequest) (*PinListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPinServiceServer) GetValue(context.Context, *pb.Id) (*pb.PinValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedPinServiceServer) SetValue(context.Context, *pb.PinValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedPinServiceServer) GetValueByName(context.Context, *pb.Name) (*pb.PinNameValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValueByName not implemented")
}
func (UnimplementedPinServiceServer) SetValueByName(context.Context, *pb.PinNameValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValueByName not implemented")
}
func (UnimplementedPinServiceServer) ViewValue(context.Context, *pb.Id) (*pb.PinValueUpdated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewValue not implemented")
}
func (UnimplementedPinServiceServer) DeleteValue(context.Context, *pb.Id) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteValue not implemented")
}
func (UnimplementedPinServiceServer) PullValue(*PinPullValueRequest, grpc.ServerStreamingServer[pb.PinValueUpdated]) error {
	return status.Errorf(codes.Unimplemented, "method PullValue not implemented")
}
func (UnimplementedPinServiceServer) GetWrite(context.Context, *pb.Id) (*pb.PinValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWrite not implemented")
}
func (UnimplementedPinServiceServer) GetWriteByName(context.Context, *pb.Name) (*pb.PinNameValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWriteByName not implemented")
}
func (UnimplementedPinServiceServer) ViewWrite(context.Context, *pb.Id) (*pb.PinValueUpdated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewWrite not implemented")
}
func (UnimplementedPinServiceServer) PushWrite(grpc.ClientStreamingServer[pb.PinValueUpdated, pb.MyBool]) error {
	return status.Errorf(codes.Unimplemented, "method PushWrite not implemented")
}
func (UnimplementedPinServiceServer) mustEmbedUnimplementedPinServiceServer() {}
func (UnimplementedPinServiceServer) testEmbeddedByValue()                    {}

// UnsafePinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PinServiceServer will
// result in compilation errors.
type UnsafePinServiceServer interface {
	mustEmbedUnimplementedPinServiceServer()
}

func RegisterPinServiceServer(s grpc.ServiceRegistrar, srv PinServiceServer) {
	// If the following call pancis, it indicates UnimplementedPinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PinService_ServiceDesc, srv)
}

func _PinService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).View(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).Name(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).List(ctx, req.(*PinListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).GetValue(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.PinValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_SetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).SetValue(ctx, req.(*pb.PinValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_GetValueByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).GetValueByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_GetValueByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).GetValueByName(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_SetValueByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.PinNameValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).SetValueByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_SetValueByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).SetValueByName(ctx, req.(*pb.PinNameValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_ViewValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).ViewValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_ViewValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).ViewValue(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_DeleteValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).DeleteValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_DeleteValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).DeleteValue(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_PullValue_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PinPullValueRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PinServiceServer).PullValue(m, &grpc.GenericServerStream[PinPullValueRequest, pb.PinValueUpdated]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PinService_PullValueServer = grpc.ServerStreamingServer[pb.PinValueUpdated]

func _PinService_GetWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).GetWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_GetWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).GetWrite(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_GetWriteByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).GetWriteByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_GetWriteByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).GetWriteByName(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_ViewWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinServiceServer).ViewWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PinService_ViewWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinServiceServer).ViewWrite(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PinService_PushWrite_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PinServiceServer).PushWrite(&grpc.GenericServerStream[pb.PinValueUpdated, pb.MyBool]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PinService_PushWriteServer = grpc.ClientStreamingServer[pb.PinValueUpdated, pb.MyBool]

// PinService_ServiceDesc is the grpc.ServiceDesc for PinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edges.PinService",
	HandlerType: (*PinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "View",
			Handler:    _PinService_View_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _PinService_Name_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PinService_List_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _PinService_GetValue_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _PinService_SetValue_Handler,
		},
		{
			MethodName: "GetValueByName",
			Handler:    _PinService_GetValueByName_Handler,
		},
		{
			MethodName: "SetValueByName",
			Handler:    _PinService_SetValueByName_Handler,
		},
		{
			MethodName: "ViewValue",
			Handler:    _PinService_ViewValue_Handler,
		},
		{
			MethodName: "DeleteValue",
			Handler:    _PinService_DeleteValue_Handler,
		},
		{
			MethodName: "GetWrite",
			Handler:    _PinService_GetWrite_Handler,
		},
		{
			MethodName: "GetWriteByName",
			Handler:    _PinService_GetWriteByName_Handler,
		},
		{
			MethodName: "ViewWrite",
			Handler:    _PinService_ViewWrite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullValue",
			Handler:       _PinService_PullValue_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PushWrite",
			Handler:       _PinService_PushWrite_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "edges/wire_service.proto",
}
