// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: edges/wire_service.proto

package edges

import (
	pb "github.com/snple/beacon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WireListResponse Wire 列表响应
type WireListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wires         []*pb.Wire             `protobuf:"bytes,1,rep,name=wires,proto3" json:"wires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireListResponse) Reset() {
	*x = WireListResponse{}
	mi := &file_edges_wire_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireListResponse) ProtoMessage() {}

func (x *WireListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edges_wire_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireListResponse.ProtoReflect.Descriptor instead.
func (*WireListResponse) Descriptor() ([]byte, []int) {
	return file_edges_wire_service_proto_rawDescGZIP(), []int{0}
}

func (x *WireListResponse) GetWires() []*pb.Wire {
	if x != nil {
		return x.Wires
	}
	return nil
}

// PinListRequest Pin 列表请求
type PinListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WireId        string                 `protobuf:"bytes,1,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"` // 可选，如果为空则获取所有 Pin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListRequest) Reset() {
	*x = PinListRequest{}
	mi := &file_edges_wire_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListRequest) ProtoMessage() {}

func (x *PinListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edges_wire_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListRequest.ProtoReflect.Descriptor instead.
func (*PinListRequest) Descriptor() ([]byte, []int) {
	return file_edges_wire_service_proto_rawDescGZIP(), []int{1}
}

func (x *PinListRequest) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

// PinListResponse Pin 列表响应
type PinListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pins          []*pb.Pin              `protobuf:"bytes,1,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListResponse) Reset() {
	*x = PinListResponse{}
	mi := &file_edges_wire_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListResponse) ProtoMessage() {}

func (x *PinListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edges_wire_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListResponse.ProtoReflect.Descriptor instead.
func (*PinListResponse) Descriptor() ([]byte, []int) {
	return file_edges_wire_service_proto_rawDescGZIP(), []int{2}
}

func (x *PinListResponse) GetPins() []*pb.Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

// PinPullValueRequest 拉取点位值请求
type PinPullValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	After         int64                  `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinPullValueRequest) Reset() {
	*x = PinPullValueRequest{}
	mi := &file_edges_wire_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinPullValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinPullValueRequest) ProtoMessage() {}

func (x *PinPullValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edges_wire_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinPullValueRequest.ProtoReflect.Descriptor instead.
func (*PinPullValueRequest) Descriptor() ([]byte, []int) {
	return file_edges_wire_service_proto_rawDescGZIP(), []int{3}
}

func (x *PinPullValueRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *PinPullValueRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_edges_wire_service_proto protoreflect.FileDescriptor

const file_edges_wire_service_proto_rawDesc = "" +
	"\n" +
	"\x18edges/wire_service.proto\x12\x05edges\x1a\x12node_message.proto\x1a\x15generic_message.proto\"2\n" +
	"\x10WireListResponse\x12\x1e\n" +
	"\x05wires\x18\x01 \x03(\v2\b.pb.WireR\x05wires\")\n" +
	"\x0ePinListRequest\x12\x17\n" +
	"\awire_id\x18\x01 \x01(\tR\x06wireId\".\n" +
	"\x0fPinListResponse\x12\x1b\n" +
	"\x04pins\x18\x01 \x03(\v2\a.pb.PinR\x04pins\"A\n" +
	"\x13PinPullValueRequest\x12\x14\n" +
	"\x05after\x18\x01 \x01(\x03R\x05after\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit2w\n" +
	"\vWireService\x12\x1a\n" +
	"\x04View\x12\x06.pb.Id\x1a\b.pb.Wire\"\x00\x12\x1c\n" +
	"\x04Name\x12\b.pb.Name\x1a\b.pb.Wire\"\x00\x12.\n" +
	"\x04List\x12\v.pb.MyEmpty\x1a\x17.edges.WireListResponse\"\x002}\n" +
	"\n" +
	"PinService\x12\x19\n" +
	"\x04View\x12\x06.pb.Id\x1a\a.pb.Pin\"\x00\x12\x1b\n" +
	"\x04Name\x12\b.pb.Name\x1a\a.pb.Pin\"\x00\x127\n" +
	"\x04List\x12\x15.edges.PinListRequest\x1a\x16.edges.PinListResponse\"\x002\x9f\x02\n" +
	"\x0fPinValueService\x12\"\n" +
	"\bGetValue\x12\x06.pb.Id\x1a\f.pb.PinValue\"\x00\x12&\n" +
	"\bSetValue\x12\f.pb.PinValue\x1a\n" +
	".pb.MyBool\"\x00\x12.\n" +
	"\x0eGetValueByName\x12\b.pb.Name\x1a\x10.pb.PinNameValue\"\x00\x120\n" +
	"\x0eSetValueByName\x12\x10.pb.PinNameValue\x1a\n" +
	".pb.MyBool\"\x00\x12#\n" +
	"\vDeleteValue\x12\x06.pb.Id\x1a\n" +
	".pb.MyBool\"\x00\x129\n" +
	"\tPullValue\x12\x1a.edges.PinPullValueRequest\x1a\f.pb.PinValue\"\x000\x012\x90\x01\n" +
	"\x0fPinWriteService\x12\"\n" +
	"\bGetWrite\x12\x06.pb.Id\x1a\f.pb.PinValue\"\x00\x12.\n" +
	"\x0eGetWriteByName\x12\b.pb.Name\x1a\x10.pb.PinNameValue\"\x00\x12)\n" +
	"\tPushWrite\x12\f.pb.PinValue\x1a\n" +
	".pb.MyBool\"\x00(\x01B(Z&github.com/snple/beacon/pb/edges;edgesb\x06proto3"

var (
	file_edges_wire_service_proto_rawDescOnce sync.Once
	file_edges_wire_service_proto_rawDescData []byte
)

func file_edges_wire_service_proto_rawDescGZIP() []byte {
	file_edges_wire_service_proto_rawDescOnce.Do(func() {
		file_edges_wire_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edges_wire_service_proto_rawDesc), len(file_edges_wire_service_proto_rawDesc)))
	})
	return file_edges_wire_service_proto_rawDescData
}

var file_edges_wire_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_edges_wire_service_proto_goTypes = []any{
	(*WireListResponse)(nil),    // 0: edges.WireListResponse
	(*PinListRequest)(nil),      // 1: edges.PinListRequest
	(*PinListResponse)(nil),     // 2: edges.PinListResponse
	(*PinPullValueRequest)(nil), // 3: edges.PinPullValueRequest
	(*pb.Wire)(nil),             // 4: pb.Wire
	(*pb.Pin)(nil),              // 5: pb.Pin
	(*pb.Id)(nil),               // 6: pb.Id
	(*pb.Name)(nil),             // 7: pb.Name
	(*pb.MyEmpty)(nil),          // 8: pb.MyEmpty
	(*pb.PinValue)(nil),         // 9: pb.PinValue
	(*pb.PinNameValue)(nil),     // 10: pb.PinNameValue
	(*pb.MyBool)(nil),           // 11: pb.MyBool
}
var file_edges_wire_service_proto_depIdxs = []int32{
	4,  // 0: edges.WireListResponse.wires:type_name -> pb.Wire
	5,  // 1: edges.PinListResponse.pins:type_name -> pb.Pin
	6,  // 2: edges.WireService.View:input_type -> pb.Id
	7,  // 3: edges.WireService.Name:input_type -> pb.Name
	8,  // 4: edges.WireService.List:input_type -> pb.MyEmpty
	6,  // 5: edges.PinService.View:input_type -> pb.Id
	7,  // 6: edges.PinService.Name:input_type -> pb.Name
	1,  // 7: edges.PinService.List:input_type -> edges.PinListRequest
	6,  // 8: edges.PinValueService.GetValue:input_type -> pb.Id
	9,  // 9: edges.PinValueService.SetValue:input_type -> pb.PinValue
	7,  // 10: edges.PinValueService.GetValueByName:input_type -> pb.Name
	10, // 11: edges.PinValueService.SetValueByName:input_type -> pb.PinNameValue
	6,  // 12: edges.PinValueService.DeleteValue:input_type -> pb.Id
	3,  // 13: edges.PinValueService.PullValue:input_type -> edges.PinPullValueRequest
	6,  // 14: edges.PinWriteService.GetWrite:input_type -> pb.Id
	7,  // 15: edges.PinWriteService.GetWriteByName:input_type -> pb.Name
	9,  // 16: edges.PinWriteService.PushWrite:input_type -> pb.PinValue
	4,  // 17: edges.WireService.View:output_type -> pb.Wire
	4,  // 18: edges.WireService.Name:output_type -> pb.Wire
	0,  // 19: edges.WireService.List:output_type -> edges.WireListResponse
	5,  // 20: edges.PinService.View:output_type -> pb.Pin
	5,  // 21: edges.PinService.Name:output_type -> pb.Pin
	2,  // 22: edges.PinService.List:output_type -> edges.PinListResponse
	9,  // 23: edges.PinValueService.GetValue:output_type -> pb.PinValue
	11, // 24: edges.PinValueService.SetValue:output_type -> pb.MyBool
	10, // 25: edges.PinValueService.GetValueByName:output_type -> pb.PinNameValue
	11, // 26: edges.PinValueService.SetValueByName:output_type -> pb.MyBool
	11, // 27: edges.PinValueService.DeleteValue:output_type -> pb.MyBool
	9,  // 28: edges.PinValueService.PullValue:output_type -> pb.PinValue
	9,  // 29: edges.PinWriteService.GetWrite:output_type -> pb.PinValue
	10, // 30: edges.PinWriteService.GetWriteByName:output_type -> pb.PinNameValue
	11, // 31: edges.PinWriteService.PushWrite:output_type -> pb.MyBool
	17, // [17:32] is the sub-list for method output_type
	2,  // [2:17] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_edges_wire_service_proto_init() }
func file_edges_wire_service_proto_init() {
	if File_edges_wire_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edges_wire_service_proto_rawDesc), len(file_edges_wire_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_edges_wire_service_proto_goTypes,
		DependencyIndexes: file_edges_wire_service_proto_depIdxs,
		MessageInfos:      file_edges_wire_service_proto_msgTypes,
	}.Build()
	File_edges_wire_service_proto = out.File
	file_edges_wire_service_proto_goTypes = nil
	file_edges_wire_service_proto_depIdxs = nil
}
