// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: cores/node_service.proto

package cores

import (
	pb "github.com/snple/beacon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeListResponse 节点列表响应
type NodeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*pb.Node             `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListResponse) Reset() {
	*x = NodeListResponse{}
	mi := &file_cores_node_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListResponse) ProtoMessage() {}

func (x *NodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cores_node_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListResponse.ProtoReflect.Descriptor instead.
func (*NodeListResponse) Descriptor() ([]byte, []int) {
	return file_cores_node_service_proto_rawDescGZIP(), []int{0}
}

func (x *NodeListResponse) GetNodes() []*pb.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// NodePushRequest 节点配置推送请求
type NodePushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nson          []byte                 `protobuf:"bytes,2,opt,name=nson,proto3" json:"nson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePushRequest) Reset() {
	*x = NodePushRequest{}
	mi := &file_cores_node_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePushRequest) ProtoMessage() {}

func (x *NodePushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_node_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePushRequest.ProtoReflect.Descriptor instead.
func (*NodePushRequest) Descriptor() ([]byte, []int) {
	return file_cores_node_service_proto_rawDescGZIP(), []int{1}
}

func (x *NodePushRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodePushRequest) GetNson() []byte {
	if x != nil {
		return x.Nson
	}
	return nil
}

// NodeSecretRequest 设置节点密钥请求
type NodeSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSecretRequest) Reset() {
	*x = NodeSecretRequest{}
	mi := &file_cores_node_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSecretRequest) ProtoMessage() {}

func (x *NodeSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_node_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSecretRequest.ProtoReflect.Descriptor instead.
func (*NodeSecretRequest) Descriptor() ([]byte, []int) {
	return file_cores_node_service_proto_rawDescGZIP(), []int{2}
}

func (x *NodeSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeSecretRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_cores_node_service_proto protoreflect.FileDescriptor

const file_cores_node_service_proto_rawDesc = "" +
	"\n" +
	"\x18cores/node_service.proto\x12\x05cores\x1a\x12node_message.proto\x1a\x15generic_message.proto\"2\n" +
	"\x10NodeListResponse\x12\x1e\n" +
	"\x05nodes\x18\x01 \x03(\v2\b.pb.NodeR\x05nodes\"5\n" +
	"\x0fNodePushRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04nson\x18\x02 \x01(\fR\x04nson\";\n" +
	"\x11NodeSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret2\x9e\x02\n" +
	"\vNodeService\x12\x1a\n" +
	"\x04View\x12\x06.pb.Id\x1a\b.pb.Node\"\x00\x12\x1c\n" +
	"\x04Name\x12\b.pb.Name\x1a\b.pb.Node\"\x00\x12.\n" +
	"\x04List\x12\v.pb.MyEmpty\x1a\x17.cores.NodeListResponse\"\x00\x12,\n" +
	"\x04Push\x12\x16.cores.NodePushRequest\x1a\n" +
	".pb.MyBool\"\x00\x12\x1e\n" +
	"\x06Delete\x12\x06.pb.Id\x1a\n" +
	".pb.MyBool\"\x00\x123\n" +
	"\tSetSecret\x12\x18.cores.NodeSecretRequest\x1a\n" +
	".pb.MyBool\"\x00\x12\"\n" +
	"\tGetSecret\x12\x06.pb.Id\x1a\v.pb.Message\"\x00B(Z&github.com/snple/beacon/pb/cores;coresb\x06proto3"

var (
	file_cores_node_service_proto_rawDescOnce sync.Once
	file_cores_node_service_proto_rawDescData []byte
)

func file_cores_node_service_proto_rawDescGZIP() []byte {
	file_cores_node_service_proto_rawDescOnce.Do(func() {
		file_cores_node_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cores_node_service_proto_rawDesc), len(file_cores_node_service_proto_rawDesc)))
	})
	return file_cores_node_service_proto_rawDescData
}

var file_cores_node_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cores_node_service_proto_goTypes = []any{
	(*NodeListResponse)(nil),  // 0: cores.NodeListResponse
	(*NodePushRequest)(nil),   // 1: cores.NodePushRequest
	(*NodeSecretRequest)(nil), // 2: cores.NodeSecretRequest
	(*pb.Node)(nil),           // 3: pb.Node
	(*pb.Id)(nil),             // 4: pb.Id
	(*pb.Name)(nil),           // 5: pb.Name
	(*pb.MyEmpty)(nil),        // 6: pb.MyEmpty
	(*pb.MyBool)(nil),         // 7: pb.MyBool
	(*pb.Message)(nil),        // 8: pb.Message
}
var file_cores_node_service_proto_depIdxs = []int32{
	3, // 0: cores.NodeListResponse.nodes:type_name -> pb.Node
	4, // 1: cores.NodeService.View:input_type -> pb.Id
	5, // 2: cores.NodeService.Name:input_type -> pb.Name
	6, // 3: cores.NodeService.List:input_type -> pb.MyEmpty
	1, // 4: cores.NodeService.Push:input_type -> cores.NodePushRequest
	4, // 5: cores.NodeService.Delete:input_type -> pb.Id
	2, // 6: cores.NodeService.SetSecret:input_type -> cores.NodeSecretRequest
	4, // 7: cores.NodeService.GetSecret:input_type -> pb.Id
	3, // 8: cores.NodeService.View:output_type -> pb.Node
	3, // 9: cores.NodeService.Name:output_type -> pb.Node
	0, // 10: cores.NodeService.List:output_type -> cores.NodeListResponse
	7, // 11: cores.NodeService.Push:output_type -> pb.MyBool
	7, // 12: cores.NodeService.Delete:output_type -> pb.MyBool
	7, // 13: cores.NodeService.SetSecret:output_type -> pb.MyBool
	8, // 14: cores.NodeService.GetSecret:output_type -> pb.Message
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cores_node_service_proto_init() }
func file_cores_node_service_proto_init() {
	if File_cores_node_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cores_node_service_proto_rawDesc), len(file_cores_node_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cores_node_service_proto_goTypes,
		DependencyIndexes: file_cores_node_service_proto_depIdxs,
		MessageInfos:      file_cores_node_service_proto_msgTypes,
	}.Build()
	File_cores_node_service_proto = out.File
	file_cores_node_service_proto_goTypes = nil
	file_cores_node_service_proto_depIdxs = nil
}
