// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: cores/node_service.proto

package cores

import (
	pb "github.com/snple/beacon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Tags          string                 `protobuf:"bytes,2,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListRequest) Reset() {
	*x = NodeListRequest{}
	mi := &file_cores_node_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListRequest) ProtoMessage() {}

func (x *NodeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_node_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListRequest.ProtoReflect.Descriptor instead.
func (*NodeListRequest) Descriptor() ([]byte, []int) {
	return file_cores_node_service_proto_rawDescGZIP(), []int{0}
}

func (x *NodeListRequest) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *NodeListRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type NodeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Nodes         []*pb.Node             `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListResponse) Reset() {
	*x = NodeListResponse{}
	mi := &file_cores_node_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListResponse) ProtoMessage() {}

func (x *NodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cores_node_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListResponse.ProtoReflect.Descriptor instead.
func (*NodeListResponse) Descriptor() ([]byte, []int) {
	return file_cores_node_service_proto_rawDescGZIP(), []int{1}
}

func (x *NodeListResponse) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *NodeListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *NodeListResponse) GetNodes() []*pb.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_cores_node_service_proto protoreflect.FileDescriptor

const file_cores_node_service_proto_rawDesc = "" +
	"\n" +
	"\x18cores/node_service.proto\x12\x05cores\x1a\x12node_message.proto\x1a\x15generic_message.proto\"C\n" +
	"\x0fNodeListRequest\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x12\n" +
	"\x04tags\x18\x02 \x01(\tR\x04tags\"f\n" +
	"\x10NodeListResponse\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1e\n" +
	"\x05nodes\x18\x03 \x03(\v2\b.pb.NodeR\x05nodes2\x80\x02\n" +
	"\vNodeService\x12\x1e\n" +
	"\x06Create\x12\b.pb.Node\x1a\b.pb.Node\"\x00\x12\x1e\n" +
	"\x06Update\x12\b.pb.Node\x1a\b.pb.Node\"\x00\x12\x1e\n" +
	"\x06Delete\x12\x06.pb.Id\x1a\n" +
	".pb.MyBool\"\x00\x12\x1a\n" +
	"\x04View\x12\x06.pb.Id\x1a\b.pb.Node\"\x00\x12\x1c\n" +
	"\x04Name\x12\b.pb.Name\x1a\b.pb.Node\"\x00\x129\n" +
	"\x04List\x12\x16.cores.NodeListRequest\x1a\x17.cores.NodeListResponse\"\x00\x12\x1c\n" +
	"\x04Push\x12\x06.pb.Id\x1a\n" +
	".pb.MyBool\"\x00B(Z&github.com/snple/beacon/pb/cores;coresb\x06proto3"

var (
	file_cores_node_service_proto_rawDescOnce sync.Once
	file_cores_node_service_proto_rawDescData []byte
)

func file_cores_node_service_proto_rawDescGZIP() []byte {
	file_cores_node_service_proto_rawDescOnce.Do(func() {
		file_cores_node_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cores_node_service_proto_rawDesc), len(file_cores_node_service_proto_rawDesc)))
	})
	return file_cores_node_service_proto_rawDescData
}

var file_cores_node_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cores_node_service_proto_goTypes = []any{
	(*NodeListRequest)(nil),  // 0: cores.NodeListRequest
	(*NodeListResponse)(nil), // 1: cores.NodeListResponse
	(*pb.Page)(nil),          // 2: pb.Page
	(*pb.Node)(nil),          // 3: pb.Node
	(*pb.Id)(nil),            // 4: pb.Id
	(*pb.Name)(nil),          // 5: pb.Name
	(*pb.MyBool)(nil),        // 6: pb.MyBool
}
var file_cores_node_service_proto_depIdxs = []int32{
	2,  // 0: cores.NodeListRequest.page:type_name -> pb.Page
	2,  // 1: cores.NodeListResponse.page:type_name -> pb.Page
	3,  // 2: cores.NodeListResponse.nodes:type_name -> pb.Node
	3,  // 3: cores.NodeService.Create:input_type -> pb.Node
	3,  // 4: cores.NodeService.Update:input_type -> pb.Node
	4,  // 5: cores.NodeService.Delete:input_type -> pb.Id
	4,  // 6: cores.NodeService.View:input_type -> pb.Id
	5,  // 7: cores.NodeService.Name:input_type -> pb.Name
	0,  // 8: cores.NodeService.List:input_type -> cores.NodeListRequest
	4,  // 9: cores.NodeService.Push:input_type -> pb.Id
	3,  // 10: cores.NodeService.Create:output_type -> pb.Node
	3,  // 11: cores.NodeService.Update:output_type -> pb.Node
	6,  // 12: cores.NodeService.Delete:output_type -> pb.MyBool
	3,  // 13: cores.NodeService.View:output_type -> pb.Node
	3,  // 14: cores.NodeService.Name:output_type -> pb.Node
	1,  // 15: cores.NodeService.List:output_type -> cores.NodeListResponse
	6,  // 16: cores.NodeService.Push:output_type -> pb.MyBool
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_cores_node_service_proto_init() }
func file_cores_node_service_proto_init() {
	if File_cores_node_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cores_node_service_proto_rawDesc), len(file_cores_node_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cores_node_service_proto_goTypes,
		DependencyIndexes: file_cores_node_service_proto_depIdxs,
		MessageInfos:      file_cores_node_service_proto_msgTypes,
	}.Build()
	File_cores_node_service_proto = out.File
	file_cores_node_service_proto_goTypes = nil
	file_cores_node_service_proto_depIdxs = nil
}
