// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: cores/wire_service.proto

package cores

import (
	pb "github.com/snple/beacon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WireViewRequest 获取 Wire 请求
type WireViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WireId        string                 `protobuf:"bytes,2,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireViewRequest) Reset() {
	*x = WireViewRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireViewRequest) ProtoMessage() {}

func (x *WireViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireViewRequest.ProtoReflect.Descriptor instead.
func (*WireViewRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{0}
}

func (x *WireViewRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WireViewRequest) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

// WireNameRequest 按名称获取 Wire 请求
type WireNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireNameRequest) Reset() {
	*x = WireNameRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireNameRequest) ProtoMessage() {}

func (x *WireNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireNameRequest.ProtoReflect.Descriptor instead.
func (*WireNameRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{1}
}

func (x *WireNameRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WireNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// WireListRequest 获取 Wire 列表请求
type WireListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireListRequest) Reset() {
	*x = WireListRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireListRequest) ProtoMessage() {}

func (x *WireListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireListRequest.ProtoReflect.Descriptor instead.
func (*WireListRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{2}
}

func (x *WireListRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// WireListResponse Wire 列表响应
type WireListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wires         []*pb.Wire             `protobuf:"bytes,1,rep,name=wires,proto3" json:"wires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireListResponse) Reset() {
	*x = WireListResponse{}
	mi := &file_cores_wire_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireListResponse) ProtoMessage() {}

func (x *WireListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireListResponse.ProtoReflect.Descriptor instead.
func (*WireListResponse) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{3}
}

func (x *WireListResponse) GetWires() []*pb.Wire {
	if x != nil {
		return x.Wires
	}
	return nil
}

// PinViewRequest 获取 Pin 请求
type PinViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PinId         string                 `protobuf:"bytes,2,opt,name=pin_id,json=pinId,proto3" json:"pin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinViewRequest) Reset() {
	*x = PinViewRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinViewRequest) ProtoMessage() {}

func (x *PinViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinViewRequest.ProtoReflect.Descriptor instead.
func (*PinViewRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{4}
}

func (x *PinViewRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinViewRequest) GetPinId() string {
	if x != nil {
		return x.PinId
	}
	return ""
}

// PinNameRequest 按名称获取 Pin 请求
type PinNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinNameRequest) Reset() {
	*x = PinNameRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinNameRequest) ProtoMessage() {}

func (x *PinNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinNameRequest.ProtoReflect.Descriptor instead.
func (*PinNameRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{5}
}

func (x *PinNameRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// PinListRequest 获取 Pin 列表请求
type PinListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WireId        string                 `protobuf:"bytes,2,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"` // 可选，如果为空则获取节点的所有 Pin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListRequest) Reset() {
	*x = PinListRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListRequest) ProtoMessage() {}

func (x *PinListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListRequest.ProtoReflect.Descriptor instead.
func (*PinListRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{6}
}

func (x *PinListRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinListRequest) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

// PinListResponse Pin 列表响应
type PinListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pins          []*pb.Pin              `protobuf:"bytes,1,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListResponse) Reset() {
	*x = PinListResponse{}
	mi := &file_cores_wire_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListResponse) ProtoMessage() {}

func (x *PinListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListResponse.ProtoReflect.Descriptor instead.
func (*PinListResponse) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{7}
}

func (x *PinListResponse) GetPins() []*pb.Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

// PinNameValueRequest 按名称设置点位值请求
type PinNameValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         *pb.NsonValue          `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinNameValueRequest) Reset() {
	*x = PinNameValueRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinNameValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinNameValueRequest) ProtoMessage() {}

func (x *PinNameValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinNameValueRequest.ProtoReflect.Descriptor instead.
func (*PinNameValueRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{8}
}

func (x *PinNameValueRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinNameValueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PinNameValueRequest) GetValue() *pb.NsonValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// PinPullWriteRequest 拉取写入值请求
type PinPullWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	After         int64                  `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinPullWriteRequest) Reset() {
	*x = PinPullWriteRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinPullWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinPullWriteRequest) ProtoMessage() {}

func (x *PinPullWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinPullWriteRequest.ProtoReflect.Descriptor instead.
func (*PinPullWriteRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{9}
}

func (x *PinPullWriteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinPullWriteRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *PinPullWriteRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_cores_wire_service_proto protoreflect.FileDescriptor

const file_cores_wire_service_proto_rawDesc = "" +
	"\n" +
	"\x18cores/wire_service.proto\x12\x05cores\x1a\x12node_message.proto\x1a\x15generic_message.proto\x1a\n" +
	"nson.proto\"C\n" +
	"\x0fWireViewRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\awire_id\x18\x02 \x01(\tR\x06wireId\">\n" +
	"\x0fWireNameRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x0fWireListRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"2\n" +
	"\x10WireListResponse\x12\x1e\n" +
	"\x05wires\x18\x01 \x03(\v2\b.pb.WireR\x05wires\"@\n" +
	"\x0ePinViewRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06pin_id\x18\x02 \x01(\tR\x05pinId\"=\n" +
	"\x0ePinNameRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"B\n" +
	"\x0ePinListRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\awire_id\x18\x02 \x01(\tR\x06wireId\".\n" +
	"\x0fPinListResponse\x12\x1b\n" +
	"\x04pins\x18\x01 \x03(\v2\a.pb.PinR\x04pins\"g\n" +
	"\x13PinNameValueRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\x05value\x18\x03 \x01(\v2\r.pb.NsonValueR\x05value\"Z\n" +
	"\x13PinPullWriteRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x03R\x05after\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit2\xc2\x01\n" +
	"\vWireService\x12*\n" +
	"\x04View\x12\x16.cores.WireViewRequest\x1a\b.pb.Wire\"\x00\x12*\n" +
	"\x04Name\x12\x16.cores.WireNameRequest\x1a\b.pb.Wire\"\x00\x12 \n" +
	"\bNameFull\x12\b.pb.Name\x1a\b.pb.Wire\"\x00\x129\n" +
	"\x04List\x12\x16.cores.WireListRequest\x1a\x17.cores.WireListResponse\"\x002\xba\x01\n" +
	"\n" +
	"PinService\x12(\n" +
	"\x04View\x12\x15.cores.PinViewRequest\x1a\a.pb.Pin\"\x00\x12(\n" +
	"\x04Name\x12\x15.cores.PinNameRequest\x1a\a.pb.Pin\"\x00\x12\x1f\n" +
	"\bNameFull\x12\b.pb.Name\x1a\a.pb.Pin\"\x00\x127\n" +
	"\x04List\x12\x15.cores.PinListRequest\x1a\x16.cores.PinListResponse\"\x002\x81\x02\n" +
	"\x0fPinValueService\x12\"\n" +
	"\bGetValue\x12\x06.pb.Id\x1a\f.pb.PinValue\"\x00\x12&\n" +
	"\bSetValue\x12\f.pb.PinValue\x1a\n" +
	".pb.MyBool\"\x00\x12;\n" +
	"\x0eGetValueByName\x12\x15.cores.PinNameRequest\x1a\x10.pb.PinNameValue\"\x00\x12:\n" +
	"\x0eSetValueByName\x12\x1a.cores.PinNameValueRequest\x1a\n" +
	".pb.MyBool\"\x00\x12)\n" +
	"\tPushValue\x12\f.pb.PinValue\x1a\n" +
	".pb.MyBool\"\x00(\x012\xb6\x02\n" +
	"\x0fPinWriteService\x12\"\n" +
	"\bGetWrite\x12\x06.pb.Id\x1a\f.pb.PinValue\"\x00\x12&\n" +
	"\bSetWrite\x12\f.pb.PinValue\x1a\n" +
	".pb.MyBool\"\x00\x12;\n" +
	"\x0eGetWriteByName\x12\x15.cores.PinNameRequest\x1a\x10.pb.PinNameValue\"\x00\x12:\n" +
	"\x0eSetWriteByName\x12\x1a.cores.PinNameValueRequest\x1a\n" +
	".pb.MyBool\"\x00\x12#\n" +
	"\vDeleteWrite\x12\x06.pb.Id\x1a\n" +
	".pb.MyBool\"\x00\x129\n" +
	"\tPullWrite\x12\x1a.cores.PinPullWriteRequest\x1a\f.pb.PinValue\"\x000\x01B(Z&github.com/snple/beacon/pb/cores;coresb\x06proto3"

var (
	file_cores_wire_service_proto_rawDescOnce sync.Once
	file_cores_wire_service_proto_rawDescData []byte
)

func file_cores_wire_service_proto_rawDescGZIP() []byte {
	file_cores_wire_service_proto_rawDescOnce.Do(func() {
		file_cores_wire_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cores_wire_service_proto_rawDesc), len(file_cores_wire_service_proto_rawDesc)))
	})
	return file_cores_wire_service_proto_rawDescData
}

var file_cores_wire_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cores_wire_service_proto_goTypes = []any{
	(*WireViewRequest)(nil),     // 0: cores.WireViewRequest
	(*WireNameRequest)(nil),     // 1: cores.WireNameRequest
	(*WireListRequest)(nil),     // 2: cores.WireListRequest
	(*WireListResponse)(nil),    // 3: cores.WireListResponse
	(*PinViewRequest)(nil),      // 4: cores.PinViewRequest
	(*PinNameRequest)(nil),      // 5: cores.PinNameRequest
	(*PinListRequest)(nil),      // 6: cores.PinListRequest
	(*PinListResponse)(nil),     // 7: cores.PinListResponse
	(*PinNameValueRequest)(nil), // 8: cores.PinNameValueRequest
	(*PinPullWriteRequest)(nil), // 9: cores.PinPullWriteRequest
	(*pb.Wire)(nil),             // 10: pb.Wire
	(*pb.Pin)(nil),              // 11: pb.Pin
	(*pb.NsonValue)(nil),        // 12: pb.NsonValue
	(*pb.Name)(nil),             // 13: pb.Name
	(*pb.Id)(nil),               // 14: pb.Id
	(*pb.PinValue)(nil),         // 15: pb.PinValue
	(*pb.MyBool)(nil),           // 16: pb.MyBool
	(*pb.PinNameValue)(nil),     // 17: pb.PinNameValue
}
var file_cores_wire_service_proto_depIdxs = []int32{
	10, // 0: cores.WireListResponse.wires:type_name -> pb.Wire
	11, // 1: cores.PinListResponse.pins:type_name -> pb.Pin
	12, // 2: cores.PinNameValueRequest.value:type_name -> pb.NsonValue
	0,  // 3: cores.WireService.View:input_type -> cores.WireViewRequest
	1,  // 4: cores.WireService.Name:input_type -> cores.WireNameRequest
	13, // 5: cores.WireService.NameFull:input_type -> pb.Name
	2,  // 6: cores.WireService.List:input_type -> cores.WireListRequest
	4,  // 7: cores.PinService.View:input_type -> cores.PinViewRequest
	5,  // 8: cores.PinService.Name:input_type -> cores.PinNameRequest
	13, // 9: cores.PinService.NameFull:input_type -> pb.Name
	6,  // 10: cores.PinService.List:input_type -> cores.PinListRequest
	14, // 11: cores.PinValueService.GetValue:input_type -> pb.Id
	15, // 12: cores.PinValueService.SetValue:input_type -> pb.PinValue
	5,  // 13: cores.PinValueService.GetValueByName:input_type -> cores.PinNameRequest
	8,  // 14: cores.PinValueService.SetValueByName:input_type -> cores.PinNameValueRequest
	15, // 15: cores.PinValueService.PushValue:input_type -> pb.PinValue
	14, // 16: cores.PinWriteService.GetWrite:input_type -> pb.Id
	15, // 17: cores.PinWriteService.SetWrite:input_type -> pb.PinValue
	5,  // 18: cores.PinWriteService.GetWriteByName:input_type -> cores.PinNameRequest
	8,  // 19: cores.PinWriteService.SetWriteByName:input_type -> cores.PinNameValueRequest
	14, // 20: cores.PinWriteService.DeleteWrite:input_type -> pb.Id
	9,  // 21: cores.PinWriteService.PullWrite:input_type -> cores.PinPullWriteRequest
	10, // 22: cores.WireService.View:output_type -> pb.Wire
	10, // 23: cores.WireService.Name:output_type -> pb.Wire
	10, // 24: cores.WireService.NameFull:output_type -> pb.Wire
	3,  // 25: cores.WireService.List:output_type -> cores.WireListResponse
	11, // 26: cores.PinService.View:output_type -> pb.Pin
	11, // 27: cores.PinService.Name:output_type -> pb.Pin
	11, // 28: cores.PinService.NameFull:output_type -> pb.Pin
	7,  // 29: cores.PinService.List:output_type -> cores.PinListResponse
	15, // 30: cores.PinValueService.GetValue:output_type -> pb.PinValue
	16, // 31: cores.PinValueService.SetValue:output_type -> pb.MyBool
	17, // 32: cores.PinValueService.GetValueByName:output_type -> pb.PinNameValue
	16, // 33: cores.PinValueService.SetValueByName:output_type -> pb.MyBool
	16, // 34: cores.PinValueService.PushValue:output_type -> pb.MyBool
	15, // 35: cores.PinWriteService.GetWrite:output_type -> pb.PinValue
	16, // 36: cores.PinWriteService.SetWrite:output_type -> pb.MyBool
	17, // 37: cores.PinWriteService.GetWriteByName:output_type -> pb.PinNameValue
	16, // 38: cores.PinWriteService.SetWriteByName:output_type -> pb.MyBool
	16, // 39: cores.PinWriteService.DeleteWrite:output_type -> pb.MyBool
	15, // 40: cores.PinWriteService.PullWrite:output_type -> pb.PinValue
	22, // [22:41] is the sub-list for method output_type
	3,  // [3:22] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_cores_wire_service_proto_init() }
func file_cores_wire_service_proto_init() {
	if File_cores_wire_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cores_wire_service_proto_rawDesc), len(file_cores_wire_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_cores_wire_service_proto_goTypes,
		DependencyIndexes: file_cores_wire_service_proto_depIdxs,
		MessageInfos:      file_cores_wire_service_proto_msgTypes,
	}.Build()
	File_cores_wire_service_proto = out.File
	file_cores_wire_service_proto_goTypes = nil
	file_cores_wire_service_proto_depIdxs = nil
}
