// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: cores/wire_service.proto

package cores

import (
	pb "github.com/snple/beacon/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// wire
type WireListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Tags          string                 `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireListRequest) Reset() {
	*x = WireListRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireListRequest) ProtoMessage() {}

func (x *WireListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireListRequest.ProtoReflect.Descriptor instead.
func (*WireListRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{0}
}

func (x *WireListRequest) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *WireListRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WireListRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *WireListRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type WireListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Wires         []*pb.Wire             `protobuf:"bytes,3,rep,name=wires,proto3" json:"wires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireListResponse) Reset() {
	*x = WireListResponse{}
	mi := &file_cores_wire_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireListResponse) ProtoMessage() {}

func (x *WireListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireListResponse.ProtoReflect.Descriptor instead.
func (*WireListResponse) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{1}
}

func (x *WireListResponse) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *WireListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *WireListResponse) GetWires() []*pb.Wire {
	if x != nil {
		return x.Wires
	}
	return nil
}

type WireNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireNameRequest) Reset() {
	*x = WireNameRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireNameRequest) ProtoMessage() {}

func (x *WireNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireNameRequest.ProtoReflect.Descriptor instead.
func (*WireNameRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{2}
}

func (x *WireNameRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WireNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// pin
type PinListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WireId        string                 `protobuf:"bytes,3,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	Tags          string                 `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListRequest) Reset() {
	*x = PinListRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListRequest) ProtoMessage() {}

func (x *PinListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListRequest.ProtoReflect.Descriptor instead.
func (*PinListRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{3}
}

func (x *PinListRequest) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PinListRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinListRequest) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

func (x *PinListRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type PinListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *pb.Page               `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Pins          []*pb.Pin              `protobuf:"bytes,3,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListResponse) Reset() {
	*x = PinListResponse{}
	mi := &file_cores_wire_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListResponse) ProtoMessage() {}

func (x *PinListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListResponse.ProtoReflect.Descriptor instead.
func (*PinListResponse) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{4}
}

func (x *PinListResponse) GetPage() *pb.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PinListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PinListResponse) GetPins() []*pb.Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

type PinNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinNameRequest) Reset() {
	*x = PinNameRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinNameRequest) ProtoMessage() {}

func (x *PinNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinNameRequest.ProtoReflect.Descriptor instead.
func (*PinNameRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{5}
}

func (x *PinNameRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PinGetValueByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinGetValueByNameRequest) Reset() {
	*x = PinGetValueByNameRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinGetValueByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinGetValueByNameRequest) ProtoMessage() {}

func (x *PinGetValueByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinGetValueByNameRequest.ProtoReflect.Descriptor instead.
func (*PinGetValueByNameRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{6}
}

func (x *PinGetValueByNameRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinGetValueByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PinNameValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Updated       int64                  `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinNameValue) Reset() {
	*x = PinNameValue{}
	mi := &file_cores_wire_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinNameValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinNameValue) ProtoMessage() {}

func (x *PinNameValue) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinNameValue.ProtoReflect.Descriptor instead.
func (*PinNameValue) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{7}
}

func (x *PinNameValue) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinNameValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PinNameValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PinNameValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PinNameValue) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type PinPullWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	After         int64                  `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WireId        string                 `protobuf:"bytes,4,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinPullWriteRequest) Reset() {
	*x = PinPullWriteRequest{}
	mi := &file_cores_wire_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinPullWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinPullWriteRequest) ProtoMessage() {}

func (x *PinPullWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cores_wire_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinPullWriteRequest.ProtoReflect.Descriptor instead.
func (*PinPullWriteRequest) Descriptor() ([]byte, []int) {
	return file_cores_wire_service_proto_rawDescGZIP(), []int{8}
}

func (x *PinPullWriteRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *PinPullWriteRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PinPullWriteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinPullWriteRequest) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

var File_cores_wire_service_proto protoreflect.FileDescriptor

const file_cores_wire_service_proto_rawDesc = "" +
	"\n" +
	"\x18cores/wire_service.proto\x12\x05cores\x1a\x12wire_message.proto\x1a\x15generic_message.proto\"t\n" +
	"\x0fWireListRequest\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04tags\x18\x03 \x01(\tR\x04tags\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"f\n" +
	"\x10WireListResponse\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1e\n" +
	"\x05wires\x18\x03 \x03(\v2\b.pb.WireR\x05wires\">\n" +
	"\x0fWireNameRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"t\n" +
	"\x0ePinListRequest\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x17\n" +
	"\awire_id\x18\x03 \x01(\tR\x06wireId\x12\x12\n" +
	"\x04tags\x18\x04 \x01(\tR\x04tags\"b\n" +
	"\x0fPinListResponse\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.pb.PageR\x04page\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1b\n" +
	"\x04pins\x18\x03 \x03(\v2\a.pb.PinR\x04pins\"=\n" +
	"\x0ePinNameRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"G\n" +
	"\x18PinGetValueByNameRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"{\n" +
	"\fPinNameValue\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x18\n" +
	"\aupdated\x18\x05 \x01(\x03R\aupdated\"s\n" +
	"\x13PinPullWriteRequest\x12\x14\n" +
	"\x05after\x18\x01 \x01(\x03R\x05after\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x17\n" +
	"\awire_id\x18\x04 \x01(\tR\x06wireId2\xd4\x01\n" +
	"\vWireService\x12\x1a\n" +
	"\x04View\x12\x06.pb.Id\x1a\b.pb.Wire\"\x00\x12*\n" +
	"\x04Name\x12\x16.cores.WireNameRequest\x1a\b.pb.Wire\"\x00\x12 \n" +
	"\bNameFull\x12\b.pb.Name\x1a\b.pb.Wire\"\x00\x129\n" +
	"\x04List\x12\x16.cores.WireListRequest\x1a\x17.cores.WireListResponse\"\x00\x12 \n" +
	"\x04Push\x12\b.pb.Wire\x1a\n" +
	".pb.MyBool\"\x00(\x012\xef\x05\n" +
	"\n" +
	"PinService\x12\x19\n" +
	"\x04View\x12\x06.pb.Id\x1a\a.pb.Pin\"\x00\x12(\n" +
	"\x04Name\x12\x15.cores.PinNameRequest\x1a\a.pb.Pin\"\x00\x12\x1f\n" +
	"\bNameFull\x12\b.pb.Name\x1a\a.pb.Pin\"\x00\x127\n" +
	"\x04List\x12\x15.cores.PinListRequest\x1a\x16.cores.PinListResponse\"\x00\x12\x1f\n" +
	"\x04Push\x12\a.pb.Pin\x1a\n" +
	".pb.MyBool\"\x00(\x01\x12\"\n" +
	"\bGetValue\x12\x06.pb.Id\x1a\f.pb.PinValue\"\x00\x12H\n" +
	"\x0eGetValueByName\x12\x1f.cores.PinGetValueByNameRequest\x1a\x13.cores.PinNameValue\"\x00\x12*\n" +
	"\tViewValue\x12\x06.pb.Id\x1a\x13.pb.PinValueUpdated\"\x00\x12)\n" +
	"\tPushValue\x12\f.pb.PinValue\x1a\n" +
	".pb.MyBool\"\x00(\x01\x12\"\n" +
	"\bGetWrite\x12\x06.pb.Id\x1a\f.pb.PinValue\"\x00\x12&\n" +
	"\bSetWrite\x12\f.pb.PinValue\x1a\n" +
	".pb.MyBool\"\x00\x12H\n" +
	"\x0eGetWriteByName\x12\x1f.cores.PinGetValueByNameRequest\x1a\x13.cores.PinNameValue\"\x00\x123\n" +
	"\x0eSetWriteByName\x12\x13.cores.PinNameValue\x1a\n" +
	".pb.MyBool\"\x00\x12*\n" +
	"\tViewWrite\x12\x06.pb.Id\x1a\x13.pb.PinValueUpdated\"\x00\x12#\n" +
	"\vDeleteWrite\x12\x06.pb.Id\x1a\n" +
	".pb.MyBool\"\x00\x12@\n" +
	"\tPullWrite\x12\x1a.cores.PinPullWriteRequest\x1a\x13.pb.PinValueUpdated\"\x000\x01B(Z&github.com/snple/beacon/pb/cores;coresb\x06proto3"

var (
	file_cores_wire_service_proto_rawDescOnce sync.Once
	file_cores_wire_service_proto_rawDescData []byte
)

func file_cores_wire_service_proto_rawDescGZIP() []byte {
	file_cores_wire_service_proto_rawDescOnce.Do(func() {
		file_cores_wire_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cores_wire_service_proto_rawDesc), len(file_cores_wire_service_proto_rawDesc)))
	})
	return file_cores_wire_service_proto_rawDescData
}

var file_cores_wire_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cores_wire_service_proto_goTypes = []any{
	(*WireListRequest)(nil),          // 0: cores.WireListRequest
	(*WireListResponse)(nil),         // 1: cores.WireListResponse
	(*WireNameRequest)(nil),          // 2: cores.WireNameRequest
	(*PinListRequest)(nil),           // 3: cores.PinListRequest
	(*PinListResponse)(nil),          // 4: cores.PinListResponse
	(*PinNameRequest)(nil),           // 5: cores.PinNameRequest
	(*PinGetValueByNameRequest)(nil), // 6: cores.PinGetValueByNameRequest
	(*PinNameValue)(nil),             // 7: cores.PinNameValue
	(*PinPullWriteRequest)(nil),      // 8: cores.PinPullWriteRequest
	(*pb.Page)(nil),                  // 9: pb.Page
	(*pb.Wire)(nil),                  // 10: pb.Wire
	(*pb.Pin)(nil),                   // 11: pb.Pin
	(*pb.Id)(nil),                    // 12: pb.Id
	(*pb.Name)(nil),                  // 13: pb.Name
	(*pb.PinValue)(nil),              // 14: pb.PinValue
	(*pb.MyBool)(nil),                // 15: pb.MyBool
	(*pb.PinValueUpdated)(nil),       // 16: pb.PinValueUpdated
}
var file_cores_wire_service_proto_depIdxs = []int32{
	9,  // 0: cores.WireListRequest.page:type_name -> pb.Page
	9,  // 1: cores.WireListResponse.page:type_name -> pb.Page
	10, // 2: cores.WireListResponse.wires:type_name -> pb.Wire
	9,  // 3: cores.PinListRequest.page:type_name -> pb.Page
	9,  // 4: cores.PinListResponse.page:type_name -> pb.Page
	11, // 5: cores.PinListResponse.pins:type_name -> pb.Pin
	12, // 6: cores.WireService.View:input_type -> pb.Id
	2,  // 7: cores.WireService.Name:input_type -> cores.WireNameRequest
	13, // 8: cores.WireService.NameFull:input_type -> pb.Name
	0,  // 9: cores.WireService.List:input_type -> cores.WireListRequest
	10, // 10: cores.WireService.Push:input_type -> pb.Wire
	12, // 11: cores.PinService.View:input_type -> pb.Id
	5,  // 12: cores.PinService.Name:input_type -> cores.PinNameRequest
	13, // 13: cores.PinService.NameFull:input_type -> pb.Name
	3,  // 14: cores.PinService.List:input_type -> cores.PinListRequest
	11, // 15: cores.PinService.Push:input_type -> pb.Pin
	12, // 16: cores.PinService.GetValue:input_type -> pb.Id
	6,  // 17: cores.PinService.GetValueByName:input_type -> cores.PinGetValueByNameRequest
	12, // 18: cores.PinService.ViewValue:input_type -> pb.Id
	14, // 19: cores.PinService.PushValue:input_type -> pb.PinValue
	12, // 20: cores.PinService.GetWrite:input_type -> pb.Id
	14, // 21: cores.PinService.SetWrite:input_type -> pb.PinValue
	6,  // 22: cores.PinService.GetWriteByName:input_type -> cores.PinGetValueByNameRequest
	7,  // 23: cores.PinService.SetWriteByName:input_type -> cores.PinNameValue
	12, // 24: cores.PinService.ViewWrite:input_type -> pb.Id
	12, // 25: cores.PinService.DeleteWrite:input_type -> pb.Id
	8,  // 26: cores.PinService.PullWrite:input_type -> cores.PinPullWriteRequest
	10, // 27: cores.WireService.View:output_type -> pb.Wire
	10, // 28: cores.WireService.Name:output_type -> pb.Wire
	10, // 29: cores.WireService.NameFull:output_type -> pb.Wire
	1,  // 30: cores.WireService.List:output_type -> cores.WireListResponse
	15, // 31: cores.WireService.Push:output_type -> pb.MyBool
	11, // 32: cores.PinService.View:output_type -> pb.Pin
	11, // 33: cores.PinService.Name:output_type -> pb.Pin
	11, // 34: cores.PinService.NameFull:output_type -> pb.Pin
	4,  // 35: cores.PinService.List:output_type -> cores.PinListResponse
	15, // 36: cores.PinService.Push:output_type -> pb.MyBool
	14, // 37: cores.PinService.GetValue:output_type -> pb.PinValue
	7,  // 38: cores.PinService.GetValueByName:output_type -> cores.PinNameValue
	16, // 39: cores.PinService.ViewValue:output_type -> pb.PinValueUpdated
	15, // 40: cores.PinService.PushValue:output_type -> pb.MyBool
	14, // 41: cores.PinService.GetWrite:output_type -> pb.PinValue
	15, // 42: cores.PinService.SetWrite:output_type -> pb.MyBool
	7,  // 43: cores.PinService.GetWriteByName:output_type -> cores.PinNameValue
	15, // 44: cores.PinService.SetWriteByName:output_type -> pb.MyBool
	16, // 45: cores.PinService.ViewWrite:output_type -> pb.PinValueUpdated
	15, // 46: cores.PinService.DeleteWrite:output_type -> pb.MyBool
	16, // 47: cores.PinService.PullWrite:output_type -> pb.PinValueUpdated
	27, // [27:48] is the sub-list for method output_type
	6,  // [6:27] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_cores_wire_service_proto_init() }
func file_cores_wire_service_proto_init() {
	if File_cores_wire_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cores_wire_service_proto_rawDesc), len(file_cores_wire_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cores_wire_service_proto_goTypes,
		DependencyIndexes: file_cores_wire_service_proto_depIdxs,
		MessageInfos:      file_cores_wire_service_proto_msgTypes,
	}.Build()
	File_cores_wire_service_proto = out.File
	file_cores_wire_service_proto_goTypes = nil
	file_cores_wire_service_proto_depIdxs = nil
}
