// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: node_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node 设备节点
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Status        int32                  `protobuf:"zigzag32,4,opt,name=status,proto3" json:"status,omitempty"`
	Updated       int64                  `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_node_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_node_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_node_message_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Node) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Node) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

var File_node_message_proto protoreflect.FileDescriptor

const file_node_message_proto_rawDesc = "" +
	"\n" +
	"\x12node_message.proto\x12\x02pb\"t\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x11R\x06status\x12\x18\n" +
	"\aupdated\x18\x05 \x01(\x03R\aupdatedB\x1fZ\x1dgithub.com/snple/beacon/pb;pbb\x06proto3"

var (
	file_node_message_proto_rawDescOnce sync.Once
	file_node_message_proto_rawDescData []byte
)

func file_node_message_proto_rawDescGZIP() []byte {
	file_node_message_proto_rawDescOnce.Do(func() {
		file_node_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_message_proto_rawDesc), len(file_node_message_proto_rawDesc)))
	})
	return file_node_message_proto_rawDescData
}

var file_node_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_message_proto_goTypes = []any{
	(*Node)(nil), // 0: pb.Node
}
var file_node_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_message_proto_init() }
func file_node_message_proto_init() {
	if File_node_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_message_proto_rawDesc), len(file_node_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_message_proto_goTypes,
		DependencyIndexes: file_node_message_proto_depIdxs,
		MessageInfos:      file_node_message_proto_msgTypes,
	}.Build()
	File_node_message_proto = out.File
	file_node_message_proto_goTypes = nil
	file_node_message_proto_depIdxs = nil
}
