// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: node_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node 设备节点（完整配置，包含嵌套的 Wire 和 Pin）
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"zigzag32,3,opt,name=status,proto3" json:"status,omitempty"`
	Updated       int64                  `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Wires         []*Wire                `protobuf:"bytes,5,rep,name=wires,proto3" json:"wires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_node_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_node_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_node_message_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Node) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *Node) GetWires() []*Wire {
	if x != nil {
		return x.Wires
	}
	return nil
}

// Wire 通道配置
type Wire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Clusters      []string               `protobuf:"bytes,5,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Pins          []*Pin                 `protobuf:"bytes,6,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wire) Reset() {
	*x = Wire{}
	mi := &file_node_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wire) ProtoMessage() {}

func (x *Wire) ProtoReflect() protoreflect.Message {
	mi := &file_node_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wire.ProtoReflect.Descriptor instead.
func (*Wire) Descriptor() ([]byte, []int) {
	return file_node_message_proto_rawDescGZIP(), []int{1}
}

func (x *Wire) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wire) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wire) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Wire) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Wire) GetClusters() []string {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *Wire) GetPins() []*Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

// Pin 点位配置
type Pin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Type          uint32                 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"` // nson.DataType 类型码
	Rw            int32                  `protobuf:"zigzag32,5,opt,name=rw,proto3" json:"rw,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pin) Reset() {
	*x = Pin{}
	mi := &file_node_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pin) ProtoMessage() {}

func (x *Pin) ProtoReflect() protoreflect.Message {
	mi := &file_node_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pin.ProtoReflect.Descriptor instead.
func (*Pin) Descriptor() ([]byte, []int) {
	return file_node_message_proto_rawDescGZIP(), []int{2}
}

func (x *Pin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pin) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Pin) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Pin) GetRw() int32 {
	if x != nil {
		return x.Rw
	}
	return 0
}

func (x *Pin) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// PinValue 点位值
type PinValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         *NsonValue             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Updated       int64                  `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinValue) Reset() {
	*x = PinValue{}
	mi := &file_node_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinValue) ProtoMessage() {}

func (x *PinValue) ProtoReflect() protoreflect.Message {
	mi := &file_node_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinValue.ProtoReflect.Descriptor instead.
func (*PinValue) Descriptor() ([]byte, []int) {
	return file_node_message_proto_rawDescGZIP(), []int{3}
}

func (x *PinValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PinValue) GetValue() *NsonValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PinValue) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

// PinNameValue 按名称的点位值
type PinNameValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *NsonValue             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Updated       int64                  `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinNameValue) Reset() {
	*x = PinNameValue{}
	mi := &file_node_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinNameValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinNameValue) ProtoMessage() {}

func (x *PinNameValue) ProtoReflect() protoreflect.Message {
	mi := &file_node_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinNameValue.ProtoReflect.Descriptor instead.
func (*PinNameValue) Descriptor() ([]byte, []int) {
	return file_node_message_proto_rawDescGZIP(), []int{4}
}

func (x *PinNameValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PinNameValue) GetValue() *NsonValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PinNameValue) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

var File_node_message_proto protoreflect.FileDescriptor

const file_node_message_proto_rawDesc = "" +
	"\n" +
	"\x12node_message.proto\x12\x02pb\x1a\n" +
	"nson.proto\"|\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x11R\x06status\x12\x18\n" +
	"\aupdated\x18\x04 \x01(\x03R\aupdated\x12\x1e\n" +
	"\x05wires\x18\x05 \x03(\v2\b.pb.WireR\x05wires\"\x8b\x01\n" +
	"\x04Wire\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1a\n" +
	"\bclusters\x18\x05 \x03(\tR\bclusters\x12\x1b\n" +
	"\x04pins\x18\x06 \x03(\v2\a.pb.PinR\x04pins\"u\n" +
	"\x03Pin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12\x12\n" +
	"\x04type\x18\x04 \x01(\rR\x04type\x12\x0e\n" +
	"\x02rw\x18\x05 \x01(\x11R\x02rw\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"Y\n" +
	"\bPinValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.pb.NsonValueR\x05value\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\x03R\aupdated\"a\n" +
	"\fPinNameValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.pb.NsonValueR\x05value\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\x03R\aupdatedB\x1fZ\x1dgithub.com/snple/beacon/pb;pbb\x06proto3"

var (
	file_node_message_proto_rawDescOnce sync.Once
	file_node_message_proto_rawDescData []byte
)

func file_node_message_proto_rawDescGZIP() []byte {
	file_node_message_proto_rawDescOnce.Do(func() {
		file_node_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_message_proto_rawDesc), len(file_node_message_proto_rawDesc)))
	})
	return file_node_message_proto_rawDescData
}

var file_node_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_node_message_proto_goTypes = []any{
	(*Node)(nil),         // 0: pb.Node
	(*Wire)(nil),         // 1: pb.Wire
	(*Pin)(nil),          // 2: pb.Pin
	(*PinValue)(nil),     // 3: pb.PinValue
	(*PinNameValue)(nil), // 4: pb.PinNameValue
	(*NsonValue)(nil),    // 5: pb.NsonValue
}
var file_node_message_proto_depIdxs = []int32{
	1, // 0: pb.Node.wires:type_name -> pb.Wire
	2, // 1: pb.Wire.pins:type_name -> pb.Pin
	5, // 2: pb.PinValue.value:type_name -> pb.NsonValue
	5, // 3: pb.PinNameValue.value:type_name -> pb.NsonValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_node_message_proto_init() }
func file_node_message_proto_init() {
	if File_node_message_proto != nil {
		return
	}
	file_nson_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_message_proto_rawDesc), len(file_node_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_message_proto_goTypes,
		DependencyIndexes: file_node_message_proto_depIdxs,
		MessageInfos:      file_node_message_proto_msgTypes,
	}.Build()
	File_node_message_proto = out.File
	file_node_message_proto_goTypes = nil
	file_node_message_proto_depIdxs = nil
}
