// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: nson.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NSON 值的通用表示（支持递归结构）
type NsonValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // nson.DataType 类型码
	// Types that are valid to be assigned to Value:
	//
	//	*NsonValue_BoolValue
	//	*NsonValue_NullValue
	//	*NsonValue_FloatValue
	//	*NsonValue_DoubleValue
	//	*NsonValue_Int32Value
	//	*NsonValue_Int64Value
	//	*NsonValue_Uint32Value
	//	*NsonValue_Uint64Value
	//	*NsonValue_StringValue
	//	*NsonValue_BinaryValue
	//	*NsonValue_ArrayValue
	//	*NsonValue_MapValue
	//	*NsonValue_TimestampValue
	//	*NsonValue_IdValue
	Value         isNsonValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NsonValue) Reset() {
	*x = NsonValue{}
	mi := &file_nson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NsonValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NsonValue) ProtoMessage() {}

func (x *NsonValue) ProtoReflect() protoreflect.Message {
	mi := &file_nson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NsonValue.ProtoReflect.Descriptor instead.
func (*NsonValue) Descriptor() ([]byte, []int) {
	return file_nson_proto_rawDescGZIP(), []int{0}
}

func (x *NsonValue) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *NsonValue) GetValue() isNsonValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NsonValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *NsonValue) GetNullValue() structpb.NullValue {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_NullValue); ok {
			return x.NullValue
		}
	}
	return structpb.NullValue(0)
}

func (x *NsonValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *NsonValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *NsonValue) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *NsonValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *NsonValue) GetUint32Value() uint32 {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_Uint32Value); ok {
			return x.Uint32Value
		}
	}
	return 0
}

func (x *NsonValue) GetUint64Value() uint64 {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return 0
}

func (x *NsonValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *NsonValue) GetBinaryValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_BinaryValue); ok {
			return x.BinaryValue
		}
	}
	return nil
}

func (x *NsonValue) GetArrayValue() *NsonArray {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *NsonValue) GetMapValue() *NsonMap {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

func (x *NsonValue) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *NsonValue) GetIdValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*NsonValue_IdValue); ok {
			return x.IdValue
		}
	}
	return nil
}

type isNsonValue_Value interface {
	isNsonValue_Value()
}

type NsonValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"` // 0x01: BOOL
}

type NsonValue_NullValue struct {
	NullValue structpb.NullValue `protobuf:"varint,3,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"` // 0x02: NULL
}

type NsonValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"` // 0x11: F32
}

type NsonValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"` // 0x12: F64
}

type NsonValue_Int32Value struct {
	Int32Value int32 `protobuf:"varint,6,opt,name=int32_value,json=int32Value,proto3,oneof"` // 0x13/0x17/0x19: I32/I8/I16
}

type NsonValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,7,opt,name=int64_value,json=int64Value,proto3,oneof"` // 0x14: I64
}

type NsonValue_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,8,opt,name=uint32_value,json=uint32Value,proto3,oneof"` // 0x15/0x18/0x1A: U32/U8/U16
}

type NsonValue_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,9,opt,name=uint64_value,json=uint64Value,proto3,oneof"` // 0x16: U64
}

type NsonValue_StringValue struct {
	StringValue string `protobuf:"bytes,10,opt,name=string_value,json=stringValue,proto3,oneof"` // 0x21: STRING
}

type NsonValue_BinaryValue struct {
	BinaryValue []byte `protobuf:"bytes,11,opt,name=binary_value,json=binaryValue,proto3,oneof"` // 0x22: BINARY
}

type NsonValue_ArrayValue struct {
	ArrayValue *NsonArray `protobuf:"bytes,12,opt,name=array_value,json=arrayValue,proto3,oneof"` // 0x31: ARRAY
}

type NsonValue_MapValue struct {
	MapValue *NsonMap `protobuf:"bytes,13,opt,name=map_value,json=mapValue,proto3,oneof"` // 0x32: MAP
}

type NsonValue_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=timestamp_value,json=timestampValue,proto3,oneof"` // 0x41: TIMESTAMP
}

type NsonValue_IdValue struct {
	IdValue []byte `protobuf:"bytes,15,opt,name=id_value,json=idValue,proto3,oneof"` // 0x42: ID (12 bytes)
}

func (*NsonValue_BoolValue) isNsonValue_Value() {}

func (*NsonValue_NullValue) isNsonValue_Value() {}

func (*NsonValue_FloatValue) isNsonValue_Value() {}

func (*NsonValue_DoubleValue) isNsonValue_Value() {}

func (*NsonValue_Int32Value) isNsonValue_Value() {}

func (*NsonValue_Int64Value) isNsonValue_Value() {}

func (*NsonValue_Uint32Value) isNsonValue_Value() {}

func (*NsonValue_Uint64Value) isNsonValue_Value() {}

func (*NsonValue_StringValue) isNsonValue_Value() {}

func (*NsonValue_BinaryValue) isNsonValue_Value() {}

func (*NsonValue_ArrayValue) isNsonValue_Value() {}

func (*NsonValue_MapValue) isNsonValue_Value() {}

func (*NsonValue_TimestampValue) isNsonValue_Value() {}

func (*NsonValue_IdValue) isNsonValue_Value() {}

// NSON 数组（递归定义）
type NsonArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*NsonValue           `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NsonArray) Reset() {
	*x = NsonArray{}
	mi := &file_nson_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NsonArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NsonArray) ProtoMessage() {}

func (x *NsonArray) ProtoReflect() protoreflect.Message {
	mi := &file_nson_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NsonArray.ProtoReflect.Descriptor instead.
func (*NsonArray) Descriptor() ([]byte, []int) {
	return file_nson_proto_rawDescGZIP(), []int{1}
}

func (x *NsonArray) GetValues() []*NsonValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// NSON 映射（递归定义）
type NsonMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]*NsonValue  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NsonMap) Reset() {
	*x = NsonMap{}
	mi := &file_nson_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NsonMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NsonMap) ProtoMessage() {}

func (x *NsonMap) ProtoReflect() protoreflect.Message {
	mi := &file_nson_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NsonMap.ProtoReflect.Descriptor instead.
func (*NsonMap) Descriptor() ([]byte, []int) {
	return file_nson_proto_rawDescGZIP(), []int{2}
}

func (x *NsonMap) GetEntries() map[string]*NsonValue {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_nson_proto protoreflect.FileDescriptor

const file_nson_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"nson.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xea\x04\n" +
	"\tNsonValue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12;\n" +
	"\n" +
	"null_value\x18\x03 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\tnullValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12!\n" +
	"\vint32_value\x18\x06 \x01(\x05H\x00R\n" +
	"int32Value\x12!\n" +
	"\vint64_value\x18\a \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fuint32_value\x18\b \x01(\rH\x00R\vuint32Value\x12#\n" +
	"\fuint64_value\x18\t \x01(\x04H\x00R\vuint64Value\x12#\n" +
	"\fstring_value\x18\n" +
	" \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fbinary_value\x18\v \x01(\fH\x00R\vbinaryValue\x120\n" +
	"\varray_value\x18\f \x01(\v2\r.pb.NsonArrayH\x00R\n" +
	"arrayValue\x12*\n" +
	"\tmap_value\x18\r \x01(\v2\v.pb.NsonMapH\x00R\bmapValue\x12E\n" +
	"\x0ftimestamp_value\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12\x1b\n" +
	"\bid_value\x18\x0f \x01(\fH\x00R\aidValueB\a\n" +
	"\x05value\"2\n" +
	"\tNsonArray\x12%\n" +
	"\x06values\x18\x01 \x03(\v2\r.pb.NsonValueR\x06values\"\x88\x01\n" +
	"\aNsonMap\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.pb.NsonMap.EntriesEntryR\aentries\x1aI\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.pb.NsonValueR\x05value:\x028\x01B\x1fZ\x1dgithub.com/snple/beacon/pb;pbb\x06proto3"

var (
	file_nson_proto_rawDescOnce sync.Once
	file_nson_proto_rawDescData []byte
)

func file_nson_proto_rawDescGZIP() []byte {
	file_nson_proto_rawDescOnce.Do(func() {
		file_nson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nson_proto_rawDesc), len(file_nson_proto_rawDesc)))
	})
	return file_nson_proto_rawDescData
}

var file_nson_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nson_proto_goTypes = []any{
	(*NsonValue)(nil),             // 0: pb.NsonValue
	(*NsonArray)(nil),             // 1: pb.NsonArray
	(*NsonMap)(nil),               // 2: pb.NsonMap
	nil,                           // 3: pb.NsonMap.EntriesEntry
	(structpb.NullValue)(0),       // 4: google.protobuf.NullValue
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_nson_proto_depIdxs = []int32{
	4, // 0: pb.NsonValue.null_value:type_name -> google.protobuf.NullValue
	1, // 1: pb.NsonValue.array_value:type_name -> pb.NsonArray
	2, // 2: pb.NsonValue.map_value:type_name -> pb.NsonMap
	5, // 3: pb.NsonValue.timestamp_value:type_name -> google.protobuf.Timestamp
	0, // 4: pb.NsonArray.values:type_name -> pb.NsonValue
	3, // 5: pb.NsonMap.entries:type_name -> pb.NsonMap.EntriesEntry
	0, // 6: pb.NsonMap.EntriesEntry.value:type_name -> pb.NsonValue
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_nson_proto_init() }
func file_nson_proto_init() {
	if File_nson_proto != nil {
		return
	}
	file_nson_proto_msgTypes[0].OneofWrappers = []any{
		(*NsonValue_BoolValue)(nil),
		(*NsonValue_NullValue)(nil),
		(*NsonValue_FloatValue)(nil),
		(*NsonValue_DoubleValue)(nil),
		(*NsonValue_Int32Value)(nil),
		(*NsonValue_Int64Value)(nil),
		(*NsonValue_Uint32Value)(nil),
		(*NsonValue_Uint64Value)(nil),
		(*NsonValue_StringValue)(nil),
		(*NsonValue_BinaryValue)(nil),
		(*NsonValue_ArrayValue)(nil),
		(*NsonValue_MapValue)(nil),
		(*NsonValue_TimestampValue)(nil),
		(*NsonValue_IdValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nson_proto_rawDesc), len(file_nson_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nson_proto_goTypes,
		DependencyIndexes: file_nson_proto_depIdxs,
		MessageInfos:      file_nson_proto_msgTypes,
	}.Build()
	File_nson_proto = out.File
	file_nson_proto_goTypes = nil
	file_nson_proto_depIdxs = nil
}
