// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: wire_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wire 端点线缆
type Wire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Clusters      string                 `protobuf:"bytes,4,opt,name=clusters,proto3" json:"clusters,omitempty"`
	Updated       int64                  `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wire) Reset() {
	*x = Wire{}
	mi := &file_wire_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wire) ProtoMessage() {}

func (x *Wire) ProtoReflect() protoreflect.Message {
	mi := &file_wire_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wire.ProtoReflect.Descriptor instead.
func (*Wire) Descriptor() ([]byte, []int) {
	return file_wire_message_proto_rawDescGZIP(), []int{0}
}

func (x *Wire) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wire) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Wire) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wire) GetClusters() string {
	if x != nil {
		return x.Clusters
	}
	return ""
}

func (x *Wire) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

// Pin 属性
type Pin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WireId        string                 `protobuf:"bytes,3,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Addr          string                 `protobuf:"bytes,5,opt,name=addr,proto3" json:"addr,omitempty"`
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Rw            int32                  `protobuf:"zigzag32,8,opt,name=rw,proto3" json:"rw,omitempty"`
	Updated       int64                  `protobuf:"varint,9,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pin) Reset() {
	*x = Pin{}
	mi := &file_wire_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pin) ProtoMessage() {}

func (x *Pin) ProtoReflect() protoreflect.Message {
	mi := &file_wire_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pin.ProtoReflect.Descriptor instead.
func (*Pin) Descriptor() ([]byte, []int) {
	return file_wire_message_proto_rawDescGZIP(), []int{1}
}

func (x *Pin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pin) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Pin) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

func (x *Pin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pin) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Pin) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Pin) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Pin) GetRw() int32 {
	if x != nil {
		return x.Rw
	}
	return 0
}

func (x *Pin) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type PinValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Updated       int64                  `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinValue) Reset() {
	*x = PinValue{}
	mi := &file_wire_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinValue) ProtoMessage() {}

func (x *PinValue) ProtoReflect() protoreflect.Message {
	mi := &file_wire_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinValue.ProtoReflect.Descriptor instead.
func (*PinValue) Descriptor() ([]byte, []int) {
	return file_wire_message_proto_rawDescGZIP(), []int{2}
}

func (x *PinValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PinValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PinValue) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type PinNameValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Updated       int64                  `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinNameValue) Reset() {
	*x = PinNameValue{}
	mi := &file_wire_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinNameValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinNameValue) ProtoMessage() {}

func (x *PinNameValue) ProtoReflect() protoreflect.Message {
	mi := &file_wire_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinNameValue.ProtoReflect.Descriptor instead.
func (*PinNameValue) Descriptor() ([]byte, []int) {
	return file_wire_message_proto_rawDescGZIP(), []int{3}
}

func (x *PinNameValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PinNameValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PinNameValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PinNameValue) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type PinValueUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WireId        string                 `protobuf:"bytes,3,opt,name=wire_id,json=wireId,proto3" json:"wire_id,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Updated       int64                  `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinValueUpdated) Reset() {
	*x = PinValueUpdated{}
	mi := &file_wire_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinValueUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinValueUpdated) ProtoMessage() {}

func (x *PinValueUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_wire_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinValueUpdated.ProtoReflect.Descriptor instead.
func (*PinValueUpdated) Descriptor() ([]byte, []int) {
	return file_wire_message_proto_rawDescGZIP(), []int{4}
}

func (x *PinValueUpdated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PinValueUpdated) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PinValueUpdated) GetWireId() string {
	if x != nil {
		return x.WireId
	}
	return ""
}

func (x *PinValueUpdated) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PinValueUpdated) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

var File_wire_message_proto protoreflect.FileDescriptor

const file_wire_message_proto_rawDesc = "" +
	"\n" +
	"\x12wire_message.proto\x12\x02pb\"y\n" +
	"\x04Wire\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bclusters\x18\x04 \x01(\tR\bclusters\x12\x18\n" +
	"\aupdated\x18\x05 \x01(\x03R\aupdated\"\xc3\x01\n" +
	"\x03Pin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x17\n" +
	"\awire_id\x18\x03 \x01(\tR\x06wireId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04addr\x18\x05 \x01(\tR\x04addr\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x0e\n" +
	"\x02rw\x18\b \x01(\x11R\x02rw\x12\x18\n" +
	"\aupdated\x18\t \x01(\x03R\aupdated\"J\n" +
	"\bPinValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\x03R\aupdated\"b\n" +
	"\fPinNameValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x18\n" +
	"\aupdated\x18\x04 \x01(\x03R\aupdated\"\x83\x01\n" +
	"\x0fPinValueUpdated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x17\n" +
	"\awire_id\x18\x03 \x01(\tR\x06wireId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x18\n" +
	"\aupdated\x18\x05 \x01(\x03R\aupdatedB\x1fZ\x1dgithub.com/snple/beacon/pb;pbb\x06proto3"

var (
	file_wire_message_proto_rawDescOnce sync.Once
	file_wire_message_proto_rawDescData []byte
)

func file_wire_message_proto_rawDescGZIP() []byte {
	file_wire_message_proto_rawDescOnce.Do(func() {
		file_wire_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_message_proto_rawDesc), len(file_wire_message_proto_rawDesc)))
	})
	return file_wire_message_proto_rawDescData
}

var file_wire_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wire_message_proto_goTypes = []any{
	(*Wire)(nil),            // 0: pb.Wire
	(*Pin)(nil),             // 1: pb.Pin
	(*PinValue)(nil),        // 2: pb.PinValue
	(*PinNameValue)(nil),    // 3: pb.PinNameValue
	(*PinValueUpdated)(nil), // 4: pb.PinValueUpdated
}
var file_wire_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wire_message_proto_init() }
func file_wire_message_proto_init() {
	if File_wire_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_message_proto_rawDesc), len(file_wire_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_message_proto_goTypes,
		DependencyIndexes: file_wire_message_proto_depIdxs,
		MessageInfos:      file_wire_message_proto_msgTypes,
	}.Build()
	File_wire_message_proto = out.File
	file_wire_message_proto_goTypes = nil
	file_wire_message_proto_depIdxs = nil
}
